-- Migración 005: núcleo transaccional de infracciones e idempotencia.
-- No crea pagos, solvencias ni datos operativos.

CREATE TABLE IF NOT EXISTS idempotency_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  scope VARCHAR(80) NOT NULL,
  idempotency_key VARCHAR(191) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  resource_type VARCHAR(80) NULL,
  resource_id BIGINT UNSIGNED NULL,
  response_status SMALLINT UNSIGNED NULL,
  response_body JSON NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  expires_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_idempotency_scope_key (scope, idempotency_key),
  KEY ix_idempotency_expiry (expires_at),
  CONSTRAINT fk_idempotency_user FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT ck_idempotency_response_status CHECK (response_status IS NULL OR response_status BETWEEN 100 AND 599)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS infractions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ticket_number VARCHAR(80) NOT NULL,
  case_number VARCHAR(80) NOT NULL,
  site_id BIGINT UNSIGNED NOT NULL,
  agent_id BIGINT UNSIGNED NOT NULL,
  device_id BIGINT UNSIGNED NOT NULL,
  citizen_id BIGINT UNSIGNED NULL,
  vehicle_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'BORRADOR',
  occurred_at DATETIME(3) NOT NULL,
  driver_absent TINYINT(1) NOT NULL DEFAULT 0,
  driver_refused_signature TINYINT(1) NOT NULL DEFAULT 0,
  observations TEXT NULL,
  agent_badge_snapshot VARCHAR(50) NOT NULL,
  agent_name_snapshot VARCHAR(250) NOT NULL,
  citizen_identification_snapshot VARCHAR(150) NULL,
  citizen_name_snapshot VARCHAR(300) NULL,
  citizen_nit_snapshot VARCHAR(30) NULL,
  citizen_address_snapshot VARCHAR(500) NULL,
  vehicle_plate_snapshot VARCHAR(20) NOT NULL,
  vehicle_registration_card_snapshot VARCHAR(100) NOT NULL,
  vehicle_type_snapshot VARCHAR(100) NOT NULL,
  vehicle_brand_snapshot VARCHAR(100) NOT NULL,
  vehicle_line_snapshot VARCHAR(100) NOT NULL,
  vehicle_color_snapshot VARCHAR(80) NOT NULL,
  location_snapshot VARCHAR(500) NOT NULL,
  total_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  submitted_at DATETIME(3) NULL,
  validated_at DATETIME(3) NULL,
  validated_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_infractions_ticket_number (ticket_number),
  UNIQUE KEY uq_infractions_case_number (case_number),
  KEY ix_infractions_status_created (status, created_at),
  KEY ix_infractions_agent_status (agent_id, status),
  KEY ix_infractions_vehicle (vehicle_id, occurred_at),
  KEY ix_infractions_citizen (citizen_id, occurred_at),
  CONSTRAINT fk_infractions_site FOREIGN KEY (site_id) REFERENCES sites (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infractions_agent FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infractions_device FOREIGN KEY (device_id) REFERENCES devices (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infractions_citizen FOREIGN KEY (citizen_id) REFERENCES citizens (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infractions_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infractions_created_by FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infractions_validated_by FOREIGN KEY (validated_by_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT ck_infractions_status CHECK (status IN ('BORRADOR','PENDIENTE_VALIDACION','DEVUELTA_CORRECCION','VALIDADA','RECHAZADA','ANULADA')),
  CONSTRAINT ck_infractions_driver_flags CHECK (driver_absent IN (0,1) AND driver_refused_signature IN (0,1)),
  CONSTRAINT ck_infractions_total CHECK (total_amount >= 0),
  CONSTRAINT ck_infractions_validation CHECK ((status = 'VALIDADA' AND validated_at IS NOT NULL AND validated_by_user_id IS NOT NULL) OR status <> 'VALIDADA')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS infraction_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  infraction_id BIGINT UNSIGNED NOT NULL,
  infraction_type_id BIGINT UNSIGNED NOT NULL,
  rate_version_id BIGINT UNSIGNED NOT NULL,
  type_code_snapshot VARCHAR(30) NOT NULL,
  type_name_snapshot VARCHAR(200) NOT NULL,
  legal_basis_snapshot VARCHAR(500) NOT NULL,
  amount_snapshot DECIMAL(14,2) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_infraction_items_type (infraction_id, infraction_type_id),
  KEY ix_infraction_items_rate (rate_version_id),
  CONSTRAINT fk_infraction_items_infraction FOREIGN KEY (infraction_id) REFERENCES infractions (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infraction_items_type FOREIGN KEY (infraction_type_id) REFERENCES infraction_types (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infraction_items_rate FOREIGN KEY (rate_version_id) REFERENCES infraction_rate_versions (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT ck_infraction_items_amount CHECK (amount_snapshot > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS infraction_locations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  infraction_id BIGINT UNSIGNED NOT NULL,
  frequent_location_id BIGINT UNSIGNED NULL,
  place_name VARCHAR(250) NOT NULL,
  address VARCHAR(500) NOT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_infraction_locations_infraction (infraction_id),
  KEY ix_infraction_locations_frequent (frequent_location_id),
  CONSTRAINT fk_infraction_locations_infraction FOREIGN KEY (infraction_id) REFERENCES infractions (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_infraction_locations_frequent FOREIGN KEY (frequent_location_id) REFERENCES frequent_locations (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT ck_infraction_locations_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  CONSTRAINT ck_infraction_locations_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
