import { Router } from "express";
import type { ResultSetHeader, RowDataPacket } from "mysql2/promise";
import { z } from "zod";
import type { AppContainer } from "../../../bootstrap/container.js";
import { authenticate } from "../../../shared/http/authenticate.js";
import { authorize } from "../../../shared/http/authorize.js";
import { HttpError } from "../../../shared/http/HttpError.js";
import { getRequestId } from "../../../shared/http/request-context.js";
import { isDuplicateKey, recordOperation } from "../../../shared/http/operations.js";

const department=z.object({code:z.string().trim().min(2).max(30),name:z.string().trim().min(2).max(120),isActive:z.boolean().default(true)});
const infractionType=z.object({code:z.string().trim().min(2).max(30),name:z.string().trim().min(2).max(200),legalBasis:z.string().trim().min(2).max(500),description:z.string().trim().max(1000).nullable().optional(),requiresDriverData:z.boolean().default(false),requiresEvidence:z.boolean().default(true),isActive:z.boolean().default(true)});
const rate=z.object({infractionTypeId:z.coerce.number().int().positive(),amount:z.coerce.number().positive().multipleOf(0.01),effectiveFrom:z.iso.date(),legalReference:z.string().trim().max(500).nullable().optional(),changeReason:z.string().trim().min(3).max(500),approvedBy:z.string().trim().max(200).nullable().optional()});
const reason=z.object({category:z.enum(["INFRACTION_RETURN","INFRACTION_REJECT","INFRACTION_CANCEL","PAYMENT_REVERSE","SOLVENCY_CANCEL","APPEAL_RESOLUTION","DEVICE_BLOCK","USER_DISABLE"]),code:z.string().trim().min(2).max(40),name:z.string().trim().min(2).max(200),description:z.string().trim().max(500).nullable().optional(),requiresComment:z.boolean().default(true),requiresEvidence:z.boolean().default(false),isActive:z.boolean().default(true)});
const location=z.object({zoneId:z.coerce.number().int().positive(),code:z.string().trim().min(2).max(40),name:z.string().trim().min(2).max(200),address:z.string().trim().max(500).nullable().optional(),latitude:z.coerce.number().min(-90).max(90).nullable().optional(),longitude:z.coerce.number().min(-180).max(180).nullable().optional(),isActive:z.boolean().default(true)});
const sequence=z.object({siteId:z.coerce.number().int().positive(),documentType:z.enum(["INFRACTION","CASE_FILE","PAYMENT_ORDER","PAYMENT_RECEIPT","SOLVENCY_REQUEST","SOLVENCY","APPEAL","CASH_CLOSURE"]),sequenceYear:z.coerce.number().int().min(1900).max(2200),prefix:z.string().trim().max(30),nextNumber:z.coerce.number().int().positive().default(1),paddingLength:z.coerce.number().int().min(1).max(15).default(6)});
const list=z.object({search:z.string().trim().max(100).default(""),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(50)});

type CatalogConfig={table:string;select:string;search:string;schema:z.ZodObject;columns:Record<string,string>;module:string};
const configs:Record<string,CatalogConfig>={
 departments:{table:"departments",select:"id,code,name,is_active,created_at,updated_at",search:"code LIKE ? OR name LIKE ?",schema:department,columns:{code:"code",name:"name",isActive:"is_active"},module:"departments"},
 "infraction-types":{table:"infraction_types",select:"id,code,name,legal_basis,description,requires_driver_data,requires_evidence,is_active,created_at,updated_at",search:"code LIKE ? OR name LIKE ? OR legal_basis LIKE ?",schema:infractionType,columns:{code:"code",name:"name",legalBasis:"legal_basis",description:"description",requiresDriverData:"requires_driver_data",requiresEvidence:"requires_evidence",isActive:"is_active"},module:"infraction_types"},
 "action-reasons":{table:"action_reasons",select:"id,category,code,name,description,requires_comment,requires_evidence,is_active,created_at,updated_at",search:"code LIKE ? OR name LIKE ? OR category LIKE ?",schema:reason,columns:{category:"category",code:"code",name:"name",description:"description",requiresComment:"requires_comment",requiresEvidence:"requires_evidence",isActive:"is_active"},module:"action_reasons"},
 "frequent-locations":{table:"frequent_locations",select:"id,zone_id,code,name,address,latitude,longitude,is_active,created_at,updated_at",search:"code LIKE ? OR name LIKE ? OR address LIKE ?",schema:location,columns:{zoneId:"zone_id",code:"code",name:"name",address:"address",latitude:"latitude",longitude:"longitude",isActive:"is_active"},module:"frequent_locations"},
};

function valuesFor(input:Record<string,unknown>,columns:Record<string,string>){const names:string[]=[];const values:unknown[]=[];for(const [key,column] of Object.entries(columns))if(input[key]!==undefined){names.push(column);values.push(typeof input[key]==="boolean"?(input[key]?1:0):input[key]);}return{names,values};}

export function createCatalogRouter(container:AppContainer):Router{
 const router=Router();router.use(authenticate(container.authRepository,container.env));
 for(const [path,config] of Object.entries(configs)){
  router.get(`/${path}`,authorize("catalogs.read",container.auditRepository),async(request,response,next)=>{try{const q=list.parse(request.query);const params:unknown[]=[];let where="";if(q.search){const count=(config.search.match(/\?/g)??[]).length;where=`WHERE (${config.search})`;for(let i=0;i<count;i++)params.push(`%${q.search}%`);}const totals=await container.database.query<(RowDataPacket&{total:number})[]>(`SELECT COUNT(*) total FROM ${config.table} ${where}`,params);const rows=await container.database.query<RowDataPacket[]>(`SELECT ${config.select} FROM ${config.table} ${where} ORDER BY id DESC LIMIT ? OFFSET ?`,[...params,q.pageSize,(q.page-1)*q.pageSize]);response.json({data:rows,meta:{page:q.page,pageSize:q.pageSize,total:totals[0]?.total??0,requestId:getRequestId()}});}catch(error){next(error);}});
  router.post(`/${path}`,authorize("catalogs.manage",container.auditRepository),async(request,response,next)=>{try{const input=config.schema.parse(request.body);const {names,values}=valuesFor(input,config.columns);if(path==="infraction-types"){names.push("created_by_user_id","updated_by_user_id");values.push(request.auth?.user.id??null,request.auth?.user.id??null);}const result=await container.database.query<ResultSetHeader>(`INSERT INTO ${config.table} (${names.join(",")}) VALUES (${names.map(()=>"?").join(",")})`,values);await recordOperation(container,request,{action:"CATALOG_CREATED",module:"catalogs",entityType:config.module,entityId:String(result.insertId)});response.status(201).json({data:{id:String(result.insertId)},meta:{requestId:getRequestId()}});}catch(error){if(isDuplicateKey(error))return next(new HttpError({code:"CATALOG_DUPLICATE",message:"El código o nombre ya existe.",statusCode:409}));next(error);}});
  router.patch(`/${path}/:id`,authorize("catalogs.manage",container.auditRepository),async(request,response,next)=>{try{const id=z.coerce.number().int().positive().parse(request.params["id"]);const input=config.schema.partial().refine(value=>Object.keys(value).length>0).parse(request.body) as Record<string,unknown>;const {names,values}=valuesFor(input,config.columns);if(path==="infraction-types"){names.push("updated_by_user_id");values.push(request.auth?.user.id??null);}const result=await container.database.query<ResultSetHeader>(`UPDATE ${config.table} SET ${names.map(name=>`${name}=?`).join(",")} WHERE id=?`,[...values,id]);if(!result.affectedRows)throw new HttpError({code:"CATALOG_NOT_FOUND",message:"Registro no encontrado.",statusCode:404});await recordOperation(container,request,{action:"CATALOG_UPDATED",module:"catalogs",entityType:config.module,entityId:String(id)});response.sendStatus(204);}catch(error){if(isDuplicateKey(error))return next(new HttpError({code:"CATALOG_DUPLICATE",message:"El código o nombre ya existe.",statusCode:409}));next(error);}});
 }
 router.get("/infraction-rate-versions",authorize("catalogs.read",container.auditRepository),async(request,response,next)=>{try{const q=list.parse(request.query);const where=q.search?"WHERE it.code LIKE ? OR it.name LIKE ? OR rv.change_reason LIKE ?":"";const values=q.search?[`%${q.search}%`,`%${q.search}%`,`%${q.search}%`]:[];const rows=await container.database.query<RowDataPacket[]>(`SELECT rv.id,rv.infraction_type_id,rv.amount,rv.effective_from,rv.effective_to,rv.legal_reference,rv.change_reason,rv.approved_by,rv.created_at,it.code,it.name FROM infraction_rate_versions rv JOIN infraction_types it ON it.id=rv.infraction_type_id ${where} ORDER BY rv.effective_from DESC,rv.id DESC LIMIT ? OFFSET ?`,[...values,q.pageSize,(q.page-1)*q.pageSize]);const total=await container.database.query<(RowDataPacket&{total:number})[]>(`SELECT COUNT(*) total FROM infraction_rate_versions rv JOIN infraction_types it ON it.id=rv.infraction_type_id ${where}`,values);response.json({data:rows,meta:{page:q.page,pageSize:q.pageSize,total:total[0]?.total??0,requestId:getRequestId()}});}catch(error){next(error);}});
 router.post("/infraction-rate-versions",authorize("catalogs.manage",container.auditRepository),async(request,response,next)=>{try{const input=rate.parse(request.body);const id=await container.database.withTransaction(async(connection)=>{const [type]=await connection.query<RowDataPacket[]>("SELECT id FROM infraction_types WHERE id=? AND is_active=1 FOR UPDATE",[input.infractionTypeId]);if(!type[0])throw new HttpError({code:"INFRACTION_TYPE_NOT_FOUND",message:"Tipo de infracción activo no encontrado.",statusCode:404});await connection.query("UPDATE infraction_rate_versions SET effective_to=DATE_SUB(?,INTERVAL 1 DAY) WHERE infraction_type_id=? AND effective_to IS NULL AND effective_from < ?",[input.effectiveFrom,input.infractionTypeId,input.effectiveFrom]);const [result]=await connection.query<ResultSetHeader>(`INSERT INTO infraction_rate_versions (infraction_type_id,amount,effective_from,legal_reference,change_reason,approved_by,created_by_user_id) VALUES (?,?,?,?,?,?,?)`,[input.infractionTypeId,input.amount,input.effectiveFrom,input.legalReference??null,input.changeReason,input.approvedBy??null,request.auth?.user.id??null]);return String(result.insertId);});await recordOperation(container,request,{action:"INFRACTION_RATE_VERSION_CREATED",module:"catalogs",entityType:"infraction_rate_version",entityId:id,reason:input.changeReason});response.status(201).json({data:{id},meta:{requestId:getRequestId()}});}catch(error){if(isDuplicateKey(error))return next(new HttpError({code:"RATE_VERSION_DUPLICATE",message:"Ya existe una tarifa para esa fecha de vigencia.",statusCode:409}));next(error);}});
 router.get("/document-sequences",authorize("catalogs.read",container.auditRepository),async(request,response,next)=>{try{const q=list.parse(request.query);const where=q.search?"WHERE ds.document_type LIKE ? OR ds.prefix LIKE ? OR s.code LIKE ? OR s.name LIKE ?":"";const values=q.search?[`%${q.search}%`,`%${q.search}%`,`%${q.search}%`,`%${q.search}%`]:[];const rows=await container.database.query<RowDataPacket[]>(`SELECT ds.*,s.code site_code,s.name site_name FROM document_sequences ds JOIN sites s ON s.id=ds.site_id ${where} ORDER BY ds.sequence_year DESC,ds.document_type LIMIT ? OFFSET ?`,[...values,q.pageSize,(q.page-1)*q.pageSize]);const total=await container.database.query<(RowDataPacket&{total:number})[]>(`SELECT COUNT(*) total FROM document_sequences ds JOIN sites s ON s.id=ds.site_id ${where}`,values);response.json({data:rows,meta:{page:q.page,pageSize:q.pageSize,total:total[0]?.total??0,requestId:getRequestId()}});}catch(error){next(error);}});
 router.post("/document-sequences",authorize("catalogs.manage",container.auditRepository),async(request,response,next)=>{try{const input=sequence.parse(request.body);const result=await container.database.query<ResultSetHeader>("INSERT INTO document_sequences (site_id,document_type,sequence_year,prefix,next_number,padding_length) VALUES (?,?,?,?,?,?)",[input.siteId,input.documentType,input.sequenceYear,input.prefix,input.nextNumber,input.paddingLength]);await recordOperation(container,request,{action:"DOCUMENT_SEQUENCE_CREATED",module:"catalogs",entityType:"document_sequence",entityId:String(result.insertId)});response.status(201).json({data:{id:String(result.insertId)},meta:{requestId:getRequestId()}});}catch(error){if(isDuplicateKey(error))return next(new HttpError({code:"SEQUENCE_DUPLICATE",message:"El correlativo para sede, tipo y año ya existe.",statusCode:409}));next(error);}});
 router.patch("/document-sequences/:id",authorize("catalogs.manage",container.auditRepository),async(request,response,next)=>{try{const id=z.coerce.number().int().positive().parse(request.params["id"]);const input=sequence.partial().refine(value=>Object.keys(value).length>0).parse(request.body);const map={siteId:"site_id",documentType:"document_type",sequenceYear:"sequence_year",prefix:"prefix",nextNumber:"next_number",paddingLength:"padding_length"} as const;const names:string[]=[];const values:unknown[]=[];for(const [key,column] of Object.entries(map) as [keyof typeof map,string][])if(input[key]!==undefined){names.push(column);values.push(input[key]);}const result=await container.database.query<ResultSetHeader>(`UPDATE document_sequences SET ${names.map(name=>`${name}=?`).join(",")} WHERE id=?`,[...values,id]);if(!result.affectedRows)throw new HttpError({code:"SEQUENCE_NOT_FOUND",message:"Correlativo no encontrado.",statusCode:404});await recordOperation(container,request,{action:"DOCUMENT_SEQUENCE_UPDATED",module:"catalogs",entityType:"document_sequence",entityId:String(id)});response.sendStatus(204);}catch(error){next(error);}});
 router.post("/document-sequences/:id/next",authorize("catalogs.manage",container.auditRepository),async(request,response,next)=>{try{const id=z.coerce.number().int().positive().parse(request.params["id"]);const generated=await container.database.withTransaction(async(connection)=>{const [rows]=await connection.query<(RowDataPacket&{prefix:string;next_number:number;padding_length:number})[]>("SELECT prefix,next_number,padding_length FROM document_sequences WHERE id=? FOR UPDATE",[id]);const row=rows[0];if(!row)throw new HttpError({code:"SEQUENCE_NOT_FOUND",message:"Correlativo no encontrado.",statusCode:404});await connection.query("UPDATE document_sequences SET next_number=next_number+1 WHERE id=?",[id]);return `${row.prefix}${String(row.next_number).padStart(row.padding_length,"0")}`;});await recordOperation(container,request,{action:"DOCUMENT_NUMBER_GENERATED",module:"catalogs",entityType:"document_sequence",entityId:String(id)});response.json({data:{number:generated},meta:{requestId:getRequestId()}});}catch(error){next(error);}});
 router.get("/lookups",authorize("catalogs.read",container.auditRepository),async(_request,response,next)=>{try{const [sites,zones,departments]=await Promise.all([container.database.query<RowDataPacket[]>("SELECT id,code,name FROM sites WHERE is_active=1 ORDER BY name"),container.database.query<RowDataPacket[]>("SELECT id,code,name FROM zones WHERE is_active=1 ORDER BY name"),container.database.query<RowDataPacket[]>("SELECT id,code,name FROM departments WHERE is_active=1 ORDER BY name")]);response.json({data:{sites,zones,departments},meta:{requestId:getRequestId()}});}catch(error){next(error);}});
 return router;
}
