import { createHash, randomUUID } from "node:crypto";
import { basename, extname, resolve, sep } from "node:path";
/* eslint-disable @typescript-eslint/prefer-nullish-coalescing, @typescript-eslint/no-unnecessary-type-assertion, @typescript-eslint/return-await, @typescript-eslint/no-unnecessary-type-conversion, @typescript-eslint/consistent-indexed-object-style, @typescript-eslint/prefer-optional-chain */
import { mkdir, rm, writeFile } from "node:fs/promises";
import type { PoolConnection, ResultSetHeader, RowDataPacket } from "mysql2/promise";
import type { MySqlDatabase } from "../../../shared/infrastructure/mysql/MySqlConnection.js";
import { HttpError } from "../../../shared/http/HttpError.js";
import { applyColumnMappings, csvCell, maskMigrationValue, normalizeDeterministic, parseAndDecodeCsv, validateHeaders, validateRecord, type CsvRecord, type HistoricalEntity, type ValidatedCsvRecord } from "./HistoricalCsv.js";
import { OperationalHistoricalImporter } from "./OperationalHistoricalImporter.js";

type BatchRow=RowDataPacket&{id:number;public_reference:string;source_system:string;entity_type:HistoricalEntity;status:string;total_rows:number;valid_rows:number;rejected_rows:number;duplicate_rows:number;result_summary:unknown;backup_reference:string|null;created_by_user_id:string;created_at:Date};
type StagingRow=RowDataPacket&{id:number;row_number:number;legacy_id:string|null;raw_data:CsvRecord|string;normalized_data:CsvRecord|string|null;validation_status:string;imported_target_table:string|null;imported_target_id:number|null};
type MappingRow=RowDataPacket&{entity_type:string;mapping_type:string;source_value:string;target_entity_type:string|null;target_entity_id:number|null;target_value:string|null;version:number};
type Issue={kind:"error"|"conflict";code:string;field:string|null;message:string;value?:unknown;type?:string;candidateType?:string;candidateId?:number};

export class HistoricalMigrationService {
  private readonly importer=new OperationalHistoricalImporter();
  private readonly storageRoot:string;
  public constructor(private readonly database:MySqlDatabase,storageDirectory:string,private readonly maximumBytes:number,private readonly retentionDays:number){this.storageRoot=resolve(process.cwd(),storageDirectory);}

  public async upload(input:{content:Buffer;originalName:string;mimeType:string;sourceSystem:string;entity:HistoricalEntity;actorUserId:string}){
    this.inspectFile(input.originalName,input.mimeType,input.content);const checksum=createHash("sha256").update(input.content).digest("hex");
    const existing=await this.database.query<(BatchRow&{file_id:number})[]>(`SELECT b.*,mf.id file_id FROM migration_files mf JOIN migration_batches b ON b.id=mf.batch_id WHERE mf.entity_type=? AND mf.checksum_sha256=? LIMIT 1`,[input.entity,checksum]);if(existing[0])return {batch:existing[0],idempotentReplay:true};
    const decoded=parseAndDecodeCsv(input.content);if(decoded.records.length>100_000)throw new HttpError({code:"MIGRATION_ROW_LIMIT_EXCEEDED",message:"El archivo excede el máximo de 100000 filas.",statusCode:413});
    const reference=randomUUID();const folder=this.safePath(reference);await mkdir(folder,{recursive:true,mode:0o700});const storageKey=`${reference}/${randomUUID()}.csv`;const absolute=this.safePath(storageKey);await writeFile(absolute,input.content,{mode:0o600});
    try{
      const batchId=await this.database.withTransaction(async(connection)=>{const [batch]=await connection.query<ResultSetHeader>("INSERT INTO migration_batches (public_reference,source_system,entity_type,total_rows,created_by_user_id) VALUES (?,?,?,?,?)",[reference,input.sourceSystem,input.entity,decoded.records.length,input.actorUserId]);await connection.query("INSERT INTO migration_files (batch_id,entity_type,original_name,storage_key,mime_type,detected_encoding,size_bytes,checksum_sha256,retained_until) VALUES (?,?,?,?,?,?,?,?,DATE_ADD(UTC_TIMESTAMP(3),INTERVAL ? DAY))",[batch.insertId,input.entity,basename(input.originalName),storageKey,input.mimeType,decoded.encoding,input.content.length,checksum,this.retentionDays]);for(let offset=0;offset<decoded.records.length;offset+=250){const chunk=decoded.records.slice(offset,offset+250);const placeholders=chunk.map(()=>"(?,?,?,?,?)").join(",");const values=chunk.flatMap((record,index)=>{const raw=JSON.stringify(record);return [batch.insertId,offset+index+2,record["legacy_id"]||null,raw,createHash("sha256").update(raw).digest("hex")];});await connection.query(`INSERT INTO migration_staging_rows (batch_id,\`row_number\`,legacy_id,raw_data,row_hash) VALUES ${placeholders}`,values);}await this.execution(connection,batch.insertId,"UPLOAD","SUCCESS","Archivo cargado en staging.",input.actorUserId,null,{rows:decoded.records.length,encoding:decoded.encoding,checksum});return batch.insertId;});return {batch:await this.requireBatch(batchId),idempotentReplay:false};
    }catch(error){await writeFile(`${absolute}.orphaned`,"Carga de control fallida; eliminar mediante el procedimiento de retención.",{mode:0o600}).catch(()=>undefined);throw error;}
  }

  public async list(input:{page:number;pageSize:number;status?:string;entity?:HistoricalEntity}){const where:string[]=[];const values:unknown[]=[];if(input.status){where.push("b.status=?");values.push(input.status);}if(input.entity){where.push("b.entity_type=?");values.push(input.entity);}const clause=where.length?`WHERE ${where.join(" AND ")}`:"";const totals=await this.database.query<(RowDataPacket&{total:number})[]>(`SELECT COUNT(*) total FROM migration_batches b ${clause}`,values);const rows=await this.database.query<BatchRow[]>(`SELECT b.* FROM migration_batches b ${clause} ORDER BY b.created_at DESC,b.id DESC LIMIT ? OFFSET ?`,[...values,input.pageSize,(input.page-1)*input.pageSize]);return {rows,total:totals[0]?.total??0};}
  public async detail(id:string|number){const batch=await this.requireBatch(id);const files=await this.database.query<RowDataPacket[]>("SELECT id,original_name,mime_type,detected_encoding,size_bytes,checksum_sha256,uploaded_at,retained_until,purged_at FROM migration_files WHERE batch_id=?",[batch.id]);const logs=await this.database.query<RowDataPacket[]>("SELECT action,outcome,message,metadata,created_at FROM migration_execution_logs WHERE batch_id=? ORDER BY id DESC LIMIT 100",[batch.id]);const openConflicts=await this.count("migration_conflicts",batch.id,"status='OPEN'");const errors=await this.count("migration_validation_errors",batch.id,"severity='ERROR'");return {batch,files,logs,openConflicts,errors};}

  public async validate(id:string|number,actorUserId:string,requestId:string|null=null){const batch=await this.requireBatch(id);if(!["UPLOADED","VALIDATED","REQUIRES_REVIEW"].includes(batch.status))throw state("validar",batch.status);await this.database.query("UPDATE migration_batches SET status='VALIDATING',validation_started_at=UTC_TIMESTAMP(3),validation_finished_at=NULL WHERE id=?",[batch.id]);
    try{const rows=await this.staging(batch.id);const mappings=await this.loadMappings(batch.source_system);await this.database.withTransaction(async(connection)=>{await connection.query("DELETE FROM migration_validation_errors WHERE batch_id=?",[batch.id]);await connection.query("DELETE FROM migration_conflicts WHERE batch_id=?",[batch.id]);const firstRaw=this.asRecord(rows[0]?.raw_data??({} as CsvRecord));const mappedHeaders=Object.keys(applyColumnMappings(firstRaw,this.columnMappings(mappings,batch.entity_type)));const headerResult=validateHeaders(batch.entity_type,mappedHeaders);let valid=0;let rejected=0;let duplicates=0;const seenLegacy=new Set<string>();const seenNatural=new Map<string,number>();for(const row of rows){let record=applyColumnMappings(this.asRecord(row.raw_data),this.columnMappings(mappings,batch.entity_type));record=this.applyValueMappings(batch.entity_type,record,mappings);const issues:Issue[]=[];for(const field of headerResult.missing)issues.push({kind:"error",code:"MIGRATION_HEADER_MISSING",field,message:`Falta el encabezado obligatorio ${field}.`});for(const field of headerResult.unexpected)issues.push({kind:"error",code:"MIGRATION_HEADER_UNEXPECTED",field,message:`El encabezado ${field} no pertenece a la plantilla vigente.`});const parsed=validateRecord(batch.entity_type,record);let normalized:ValidatedCsvRecord|null=null;if(!parsed.success){for(const issue of parsed.error.issues)issues.push({kind:"error",code:"MIGRATION_FIELD_INVALID",field:String(issue.path[0]??"row"),message:issue.message,value:record[String(issue.path[0]??"")]});}else{normalized=normalizeDeterministic(batch.entity_type,parsed.data);const legacy=normalized.legacy_id;if(seenLegacy.has(legacy)){issues.push({kind:"conflict",type:"INTERNAL_DUPLICATE",code:"MIGRATION_LEGACY_DUPLICATE",field:"legacy_id",message:"El legacy_id está repetido dentro del archivo.",value:legacy});duplicates+=1;}else seenLegacy.add(legacy);const natural=this.naturalKey(batch.entity_type,normalized);if(natural){const previous=seenNatural.get(natural);if(previous){issues.push({kind:"conflict",type:"INTERNAL_DUPLICATE",code:"MIGRATION_NATURAL_DUPLICATE",field:this.naturalField(batch.entity_type),message:`El valor único ya apareció en la fila ${previous}.`,value:natural});duplicates+=1;}else seenNatural.set(natural,row.row_number);}issues.push(...await this.databaseIssues(batch,normalized,mappings));}
        const hasError=issues.some((issue)=>issue.kind==="error");const hasConflict=issues.some((issue)=>issue.kind==="conflict");const rowStatus=hasError?"INVALID":hasConflict?"CONFLICT":"VALID";if(rowStatus==="VALID")valid+=1;else rejected+=1;await connection.query("UPDATE migration_staging_rows SET legacy_id=?,normalized_data=?,validation_status=?,validated_at=UTC_TIMESTAMP(3) WHERE id=?",[normalized?.legacy_id??record["legacy_id"]??null,normalized?JSON.stringify(normalized):null,rowStatus,row.id]);for(const issue of issues)await this.persistIssue(connection,batch.id,row,issue);}
      const finalStatus=rejected===0?"VALIDATED":"REQUIRES_REVIEW";const summary={total:rows.length,valid,rejected,duplicates,errors:await this.countOn(connection,"migration_validation_errors",batch.id,"severity='ERROR'"),conflicts:await this.countOn(connection,"migration_conflicts",batch.id,"status='OPEN'")};await connection.query("UPDATE migration_batches SET status=?,valid_rows=?,rejected_rows=?,duplicate_rows=?,result_summary=?,validation_finished_at=UTC_TIMESTAMP(3) WHERE id=?",[finalStatus,valid,rejected,duplicates,JSON.stringify(summary),batch.id]);await this.execution(connection,batch.id,"VALIDATE","SUCCESS","Validación de staging completada.",actorUserId,requestId,summary);});await this.writeReviewReports(batch.id);return this.detail(batch.id);
    }catch(error){await this.database.query("UPDATE migration_batches SET status='FAILED',validation_finished_at=UTC_TIMESTAMP(3),result_summary=? WHERE id=?",[JSON.stringify({code:"VALIDATION_FAILED"}),batch.id]);await this.log(batch.id,"VALIDATE","FAILED","La validación terminó por un error técnico.",actorUserId,requestId);throw error;}
  }

  public async preview(id:string|number,page:number,pageSize:number){const batch=await this.requireBatch(id);const total=await this.count("migration_staging_rows",batch.id);const rows=await this.database.query<StagingRow[]>("SELECT id,`row_number`,legacy_id,normalized_data,validation_status,imported_target_table,imported_target_id FROM migration_staging_rows WHERE batch_id=? ORDER BY `row_number` LIMIT ? OFFSET ?",[batch.id,pageSize,(page-1)*pageSize]);return {batch,rows:rows.map((row)=>({...row,normalized_data:this.asNullableRecord(row.normalized_data)})),total};}
  public async errors(id:string|number,page:number,pageSize:number){const batch=await this.requireBatch(id);return this.pageTable("migration_validation_errors",batch.id,page,pageSize,"`row_number`,id");}
  public async conflicts(id:string|number,page:number,pageSize:number){const batch=await this.requireBatch(id);return this.pageTable("migration_conflicts",batch.id,page,pageSize,"`row_number`,id");}

  public async saveMapping(id:string|number,input:{mappingType:"TABLE"|"COLUMN"|"STATUS"|"ARTICLE"|"AGENT"|"PAYMENT_METHOD";entityType?:HistoricalEntity;sourceValue:string;targetEntityType?:string;targetEntityId?:number;targetValue?:string;conflictId?:number},actorUserId:string,requestId:string|null=null){const batch=await this.requireBatch(id);if(!["UPLOADED","VALIDATED","REQUIRES_REVIEW"].includes(batch.status))throw state("mapear",batch.status);if(!input.targetEntityId&&!input.targetValue)throw new HttpError({code:"MIGRATION_MAPPING_TARGET_REQUIRED",message:"El mapeo requiere un identificador o valor destino.",statusCode:422});const entityType=input.entityType??batch.entity_type;await this.database.withTransaction(async(connection)=>{const [versions]=await connection.query<(RowDataPacket&{version:number})[]>("SELECT COALESCE(MAX(version),0)+1 version FROM migration_entity_mappings WHERE source_system=? AND entity_type=? AND mapping_type=? AND source_value=? FOR UPDATE",[batch.source_system,entityType,input.mappingType,input.sourceValue]);await connection.query("INSERT INTO migration_entity_mappings (source_system,entity_type,mapping_type,source_value,target_entity_type,target_entity_id,target_value,version,status,created_by_user_id) VALUES (?,?,?,?,?,?,?,?, 'APPROVED',?)",[batch.source_system,entityType,input.mappingType,input.sourceValue,input.targetEntityType??null,input.targetEntityId??null,input.targetValue??null,versions[0]?.version??1,actorUserId]);if(input.conflictId)await connection.query("UPDATE migration_conflicts SET status='RESOLVED',resolution=?,resolved_by_user_id=?,resolved_at=UTC_TIMESTAMP(3) WHERE id=? AND batch_id=?",[JSON.stringify(input),actorUserId,input.conflictId,batch.id]);await this.execution(connection,batch.id,"MAP","SUCCESS","Mapeo versionado registrado.",actorUserId,requestId,{mappingType:input.mappingType,entityType,sourceValue:maskMigrationValue("mapping",input.sourceValue)});});return this.detail(batch.id);}

  public async approve(id:string|number,actorUserId:string,requestId:string|null=null){const batch=await this.requireBatch(id);if(batch.status!=="VALIDATED")throw state("aprobar",batch.status);if(batch.valid_rows!==batch.total_rows||await this.count("migration_conflicts",batch.id,"status='OPEN'")||await this.count("migration_validation_errors",batch.id,"severity='ERROR'"))throw new HttpError({code:"MIGRATION_REVIEW_PENDING",message:"El lote todavía contiene errores o conflictos sin resolver.",statusCode:409});await this.database.query("UPDATE migration_batches SET status='READY',approved_by_user_id=?,approved_at=UTC_TIMESTAMP(3) WHERE id=?",[actorUserId,batch.id]);await this.log(batch.id,"APPROVE","SUCCESS","Lote aprobado para importación.",actorUserId,requestId);return this.detail(batch.id);}

  public async commit(id:string|number,actorUserId:string,confirmation:string,requestId:string=randomUUID()){
    const batch=await this.requireBatch(id);if(batch.status==="COMPLETED")return {detail:await this.detail(batch.id),idempotentReplay:true};if(!["VALIDATED","READY"].includes(batch.status))throw state("importar",batch.status);if(confirmation!==`IMPORTAR ${batch.public_reference}`)throw new HttpError({code:"MIGRATION_CONFIRMATION_REQUIRED",message:`Escriba exactamente IMPORTAR ${batch.public_reference}.`,statusCode:409});if(batch.valid_rows!==batch.total_rows)throw new HttpError({code:"MIGRATION_INVALID_ROWS_PRESENT",message:"Solo puede importarse un lote con todas sus filas válidas.",statusCode:409});const backup=await this.createBackupManifest(batch);await this.database.query("UPDATE migration_batches SET status='IMPORTING',backup_reference=?,import_started_at=UTC_TIMESTAMP(3),imported_by_user_id=? WHERE id=?",[backup.reference,actorUserId,batch.id]);
    try{await this.database.withTransaction(async(connection)=>{const current=await this.lockBatch(connection,batch.id);if(current.status==="COMPLETED")return;if(current.status!=="IMPORTING")throw state("importar",current.status);const rows=await this.stagingOn(connection,batch.id,"VALID");let imported=0;for(let offset=0;offset<rows.length;offset+=250){for(const row of rows.slice(offset,offset+250)){const data=this.asNullableRecord(row.normalized_data);if(!data)throw new HttpError({code:"MIGRATION_NORMALIZED_DATA_MISSING",message:"La fila no tiene datos validados.",statusCode:409});const target=await this.importer.importRow(connection,batch.entity_type,data,{sourceSystem:batch.source_system,batchId:batch.id,actorUserId,requestId});await connection.query("UPDATE migration_staging_rows SET validation_status='IMPORTED',imported_target_table=?,imported_target_id=?,imported_at=UTC_TIMESTAMP(3) WHERE id=?",[target.table,target.id,row.id]);imported+=1;}}const result={imported,total:rows.length,backup:backup.reference};await connection.query("UPDATE migration_batches SET status='COMPLETED',import_finished_at=UTC_TIMESTAMP(3),result_summary=? WHERE id=?",[JSON.stringify(result),batch.id]);await this.execution(connection,batch.id,"IMPORT","SUCCESS","Importación histórica transaccional completada.",actorUserId,requestId,result);});return {detail:await this.detail(batch.id),idempotentReplay:false};
    }catch(error){await this.database.query("UPDATE migration_batches SET status='FAILED',import_finished_at=UTC_TIMESTAMP(3),result_summary=? WHERE id=?",[JSON.stringify({code:"IMPORT_ROLLED_BACK",backup:backup.reference}),batch.id]);await this.log(batch.id,"IMPORT","FAILED","La importación falló y fue revertida por la transacción.",actorUserId,requestId);throw error;}
  }

  public async revert(id:string|number,actorUserId:string,confirmation:string,requestId:string=randomUUID()){
    const batch=await this.requireBatch(id);if(batch.status==="REVERTED")return {detail:await this.detail(batch.id),idempotentReplay:true};if(batch.status!=="COMPLETED")throw state("revertir",batch.status);if(confirmation!==`REVERTIR ${batch.public_reference}`)throw new HttpError({code:"MIGRATION_CONFIRMATION_REQUIRED",message:`Escriba exactamente REVERTIR ${batch.public_reference}.`,statusCode:409});
    try{await this.database.withTransaction(async(connection)=>{await this.lockBatch(connection,batch.id);const [references]=await connection.query<(RowDataPacket&{id:number;target_table:string;target_id:number})[]>("SELECT id,target_table,target_id FROM legacy_source_references WHERE imported_by_batch_id=? AND reverted_at IS NULL ORDER BY id ASC FOR UPDATE",[batch.id]);for(const reference of references){await this.importer.revertImported(connection,reference.target_table,reference.target_id);await connection.query("UPDATE legacy_source_references SET reverted_at=UTC_TIMESTAMP(3) WHERE id=?",[reference.id]);}await connection.query("UPDATE migration_staging_rows SET validation_status='REVERTED' WHERE batch_id=? AND validation_status='IMPORTED'",[batch.id]);await connection.query("UPDATE migration_batches SET status='REVERTED',reverted_by_user_id=?,reverted_at=UTC_TIMESTAMP(3),result_summary=? WHERE id=?",[actorUserId,JSON.stringify({reverted:references.length}),batch.id]);await this.execution(connection,batch.id,"REVERT","SUCCESS","Reversión segura completada.",actorUserId,requestId,{reverted:references.length});});return {detail:await this.detail(batch.id),idempotentReplay:false};
    }catch(error){await this.log(batch.id,"REVERT","BLOCKED","La reversión fue bloqueada para proteger referencias posteriores.",actorUserId,requestId);throw error;}
  }

  public async reportCsv(id:string|number){const detail=await this.detail(id);const references=await this.database.query<(RowDataPacket&{active:number;reverted:number})[]>("SELECT SUM(reverted_at IS NULL) active,SUM(reverted_at IS NOT NULL) reverted FROM legacy_source_references WHERE imported_by_batch_id=?",[detail.batch.id]);const file=detail.files[0] as (RowDataPacket&{checksum_sha256?:string;original_name?:string})|undefined;const rows=[["Lote",detail.batch.public_reference],["Entidad",detail.batch.entity_type],["Origen",detail.batch.source_system],["Archivo",file?.original_name??""],["SHA-256",file?.checksum_sha256??""],["Estado",detail.batch.status],["Total",detail.batch.total_rows],["Válidas",detail.batch.valid_rows],["Rechazadas",detail.batch.rejected_rows],["Duplicadas",detail.batch.duplicate_rows],["Referencias activas",references[0]?.active??0],["Referencias revertidas",references[0]?.reverted??0],["Resultado",JSON.stringify(detail.batch.result_summary??{})],["Respaldo",detail.batch.backup_reference??""],["Generado",new Date().toISOString()]];return `\uFEFF${rows.map((row)=>row.map(csvCell).join(",")).join("\r\n")}\r\n`;}
  public async purgeExpiredFiles(actorUserId:string,requestId:string|null=null){const files=await this.database.query<(RowDataPacket&{id:number;batch_id:number;storage_key:string})[]>("SELECT id,batch_id,storage_key FROM migration_files WHERE purged_at IS NULL AND retained_until<UTC_TIMESTAMP(3) ORDER BY id LIMIT 1000");let purged=0;for(const file of files){await rm(this.safePath(file.storage_key),{force:true});await this.database.withTransaction(async(connection)=>{await connection.query("UPDATE migration_files SET purged_at=UTC_TIMESTAMP(3) WHERE id=? AND purged_at IS NULL",[file.id]);await this.execution(connection,file.batch_id,"PURGE","SUCCESS","Archivo histórico vencido eliminado; se conservaron hash y metadatos.",actorUserId,requestId);});purged+=1;}return {purged};}
  public templatePath(entity:HistoricalEntity){return resolve(process.cwd(),"database/templates/historical",`${entity}.csv`);}

  private inspectFile(name:string,mime:string,content:Buffer){if(name!==basename(name)||extname(name).toLowerCase()!==".csv")throw new HttpError({code:"MIGRATION_FILE_EXTENSION_INVALID",message:"Solo se admiten nombres simples con extensión .csv.",statusCode:415});if(!["text/csv","application/csv","text/plain","application/vnd.ms-excel"].includes(mime.split(";")[0]?.toLowerCase()??""))throw new HttpError({code:"MIGRATION_FILE_MIME_INVALID",message:"El MIME declarado no corresponde a CSV.",statusCode:415});if(content.length===0||content.length>this.maximumBytes)throw new HttpError({code:"MIGRATION_FILE_SIZE_INVALID",message:"El archivo está vacío o excede el límite configurado.",statusCode:413});}
  private safePath(relative:string){const candidate=resolve(this.storageRoot,relative);if(candidate!==this.storageRoot&&!candidate.startsWith(`${this.storageRoot}${sep}`))throw new HttpError({code:"MIGRATION_PATH_INVALID",message:"La ruta del archivo no es válida.",statusCode:400});return candidate;}
  private async requireBatch(id:string|number){const numeric=typeof id==="number"||/^\d+$/.test(String(id));const rows=await this.database.query<BatchRow[]>(`SELECT * FROM migration_batches WHERE ${numeric?"id":"public_reference"}=?`,[id]);if(!rows[0])throw new HttpError({code:"MIGRATION_BATCH_NOT_FOUND",message:"El lote histórico no existe.",statusCode:404});return rows[0];}
  private async lockBatch(connection:PoolConnection,id:number){const [rows]=await connection.query<BatchRow[]>("SELECT * FROM migration_batches WHERE id=? FOR UPDATE",[id]);if(!rows[0])throw new HttpError({code:"MIGRATION_BATCH_NOT_FOUND",message:"El lote histórico no existe.",statusCode:404});return rows[0];}
  private async staging(batchId:number){return this.database.query<StagingRow[]>("SELECT * FROM migration_staging_rows WHERE batch_id=? ORDER BY `row_number`",[batchId]);}
  private async stagingOn(connection:PoolConnection,batchId:number,status:string){const [rows]=await connection.query<StagingRow[]>("SELECT * FROM migration_staging_rows WHERE batch_id=? AND validation_status=? ORDER BY `row_number` FOR UPDATE",[batchId,status]);return rows;}
  private asRecord(value:CsvRecord|string):CsvRecord{return typeof value==="string"?JSON.parse(value) as CsvRecord:value;}
  private asNullableRecord(value:CsvRecord|string|null):ValidatedCsvRecord|null{return value===null?null:this.asRecord(value) as ValidatedCsvRecord;}
  private async loadMappings(source:string){const rows=await this.database.query<MappingRow[]>("SELECT entity_type,mapping_type,source_value,target_entity_type,target_entity_id,target_value,version FROM migration_entity_mappings WHERE source_system=? AND status='APPROVED' ORDER BY version DESC",[source]);const latest=new Map<string,MappingRow>();for(const row of rows){const key=this.mappingKey(row.entity_type,row.mapping_type,row.source_value);if(!latest.has(key))latest.set(key,row);}return latest;}
  private columnMappings(mappings:Map<string,MappingRow>,entity:string){const result=new Map<string,string>();for(const row of mappings.values())if(row.entity_type===entity&&row.mapping_type==="COLUMN"&&row.target_value)result.set(row.source_value,row.target_value);return result;}
  private applyValueMappings(entity:HistoricalEntity,record:CsvRecord,mappings:Map<string,MappingRow>){const result={...record};const statusMap=mappings.get(this.mappingKey(entity,"STATUS",result["status"]??""));if(statusMap?.target_value)result["status"]=statusMap.target_value;if(entity==="infraction_items"){const article=mappings.get(this.mappingKey(entity,"ARTICLE",result["article_code"]??""));if(article?.target_value)result["article_code"]=article.target_value;}if(entity==="payments"){const method=mappings.get(this.mappingKey(entity,"PAYMENT_METHOD",result["payment_method_code"]??""));if(method?.target_value)result["payment_method_code"]=method.target_value;}return result;}
  private mappingKey(entity:string,type:string,value:string){return `${entity}\u0000${type}\u0000${value}`;}
  private naturalKey(entity:HistoricalEntity,data:CsvRecord){const fields:{[K in HistoricalEntity]?:string}={citizens:"identification_normalized",vehicles:"plate_normalized",agents:"badge_number",infractions:"ticket_number",payments:"payment_order_number",receipts:"receipt_number",solvencies:"solvency_number"};const field=fields[entity];return field?`${field}:${data[field]??""}`:null;}
  private naturalField(entity:HistoricalEntity){return this.naturalKey(entity,{} as CsvRecord)?.split(":")[0]??"legacy_id";}

  private async databaseIssues(batch:BatchRow,data:ValidatedCsvRecord,mappings:Map<string,MappingRow>):Promise<Issue[]>{const issues:Issue[]=[];const existingLegacy=await this.database.query<(RowDataPacket&{target_table:string;target_id:number})[]>("SELECT target_table,target_id FROM legacy_source_references WHERE source_system=? AND entity_type=? AND legacy_id=? AND reverted_at IS NULL",[batch.source_system,batch.entity_type,data.legacy_id]);if(existingLegacy[0])issues.push(conflict("EXISTING_RECORD","legacy_id","El identificador legado ya fue importado.",data.legacy_id,existingLegacy[0].target_table,Number(existingLegacy[0].target_id)));
    const natural=await this.findNaturalExisting(batch.entity_type,data);if(natural)issues.push(conflict("EXISTING_RECORD",this.naturalField(batch.entity_type),"El registro coincide con un dato operativo existente.",this.naturalKey(batch.entity_type,data),natural.table,natural.id));
    const ref=async(entity:string,value:string|undefined,type="TABLE")=>{if(!value)return;const legacy=await this.database.query<RowDataPacket[]>("SELECT target_id FROM legacy_source_references WHERE source_system=? AND entity_type=? AND legacy_id=? AND reverted_at IS NULL",[batch.source_system,entity,value]);const mapped=mappings.get(this.mappingKey(entity,type,value));if(!legacy[0]&&!mapped?.target_entity_id)issues.push(conflict("MISSING_REFERENCE",value,"La relación legacy_id no existe ni tiene mapeo aprobado.",value,entity));};
    if(batch.entity_type==="vehicles")await ref("citizens",data.owner_legacy_id);
    if(batch.entity_type==="agents"&&!await this.exists("users","email",data.user_email,"status='ACTIVE'"))issues.push(conflict("MISSING_REFERENCE","user_email","No existe un usuario activo para el agente.",data.user_email,"users"));
    if(batch.entity_type==="infractions"){const allowed=["BORRADOR","PENDIENTE_VALIDACION","DEVUELTA_CORRECCION","VALIDADA","RECHAZADA","ANULADA"];if(!allowed.includes(data.status))issues.push(conflict("MAPPING_REQUIRED","status","El estado legado requiere mapeo humano.",data.status,"infractions"));await ref("agents",data.agent_legacy_id,"AGENT");await ref("vehicles",data.vehicle_legacy_id);await ref("citizens",data.citizen_legacy_id);if(!await this.exists("sites","code",data.site_code,"is_active=1"))issues.push(conflict("CATALOG_VALUE_UNKNOWN","site_code","La sede no pertenece al catálogo activo.",data.site_code,"sites"));if(!await this.exists("devices","device_uuid",data.device_uuid))issues.push(conflict("CATALOG_VALUE_UNKNOWN","device_uuid","El dispositivo no existe.",data.device_uuid,"devices"));}
    if(batch.entity_type==="infraction_items"){await ref("infractions",data.infraction_legacy_id);let article=await this.findId("infraction_types","code",data.article_code);const mapped=mappings.get(this.mappingKey("infraction_items","ARTICLE",data.article_code));if(!article&&mapped?.target_entity_id)article=mapped.target_entity_id;if(!article)issues.push(conflict("MAPPING_REQUIRED","article_code","El artículo legado requiere mapeo humano.",data.article_code,"infraction_types"));else if(!(await this.database.query<RowDataPacket[]>("SELECT id FROM infraction_rate_versions WHERE infraction_type_id=? AND amount=? LIMIT 1",[article,data.amount]))[0])issues.push(conflict("CATALOG_VALUE_UNKNOWN","amount","No existe una versión tarifaria del artículo con ese monto.",data.amount,"infraction_rate_versions"));}
    if(batch.entity_type==="payments"){const order=await this.database.query<(RowDataPacket&{id:number;status:string})[]>("SELECT id,status FROM payment_orders WHERE order_number=?",[data.payment_order_number]);if(!order[0])issues.push(conflict("MISSING_REFERENCE","payment_order_number","La orden no existe.",data.payment_order_number,"payment_orders"));else if(order[0].status!=="USED")issues.push(conflict("EXISTING_RECORD","payment_order_number","La orden debe constar como utilizada y no será sobrescrita.",data.payment_order_number,"payment_orders",order[0].id));if(!await this.exists("cash_sessions","id",data.cash_session_id))issues.push(conflict("MISSING_REFERENCE","cash_session_id","La sesión de caja no existe.",data.cash_session_id,"cash_sessions"));let method=await this.findId("payment_methods","code",data.payment_method_code);const mapped=mappings.get(this.mappingKey("payments","PAYMENT_METHOD",data.payment_method_code));if(!method&&mapped?.target_entity_id)method=mapped.target_entity_id;if(!method)issues.push(conflict("MAPPING_REQUIRED","payment_method_code","El método de pago requiere mapeo humano.",data.payment_method_code,"payment_methods"));}
    if(batch.entity_type==="payment_allocations"){await ref("payments",data.payment_legacy_id);await ref("infractions",data.infraction_legacy_id);}
    if(batch.entity_type==="receipts")await ref("payments",data.payment_legacy_id);
    if(batch.entity_type==="adjustments")await ref("infractions",data.infraction_legacy_id);
    if(batch.entity_type==="solvencies"){await ref("vehicles",data.vehicle_legacy_id);const request=await this.database.query<(RowDataPacket&{id:number;status:string})[]>("SELECT id,status FROM solvency_requests WHERE request_number=?",[data.solvency_request_number]);if(!request[0]||request[0].status!=="APPROVED")issues.push(conflict("MISSING_REFERENCE","solvency_request_number","La solicitud de solvencia no existe o no está aprobada.",data.solvency_request_number,"solvency_requests"));if(!await this.exists("institutional_rule_versions","id",data.validity_rule_version_id))issues.push(conflict("MISSING_REFERENCE","validity_rule_version_id","La regla de vigencia no existe.",data.validity_rule_version_id,"institutional_rule_versions"));}
    return issues;}

  private async findNaturalExisting(entity:HistoricalEntity,data:ValidatedCsvRecord):Promise<{table:string;id:number}|null>{const definitions:Partial<Record<HistoricalEntity,[string,string,string]>>={citizens:["citizens","identification_type=? AND identification_normalized=?","identification_type,identification_normalized"],vehicles:["vehicles","plate_normalized=?","plate_normalized"],agents:["agents","badge_number=?","badge_number"],infractions:["infractions","ticket_number=? OR case_number=?","ticket_number,case_number"],payments:["payments","payment_order_id=(SELECT id FROM payment_orders WHERE order_number=?)","payment_order_number"],receipts:["payment_receipts","receipt_number=?","receipt_number"],solvencies:["solvencies","solvency_number=?","solvency_number"]};const definition=definitions[entity];if(!definition)return null;const [table,where,fields]=definition;const values=fields.split(",").map((field)=>data[field]);const rows=await this.database.query<(RowDataPacket&{id:number})[]>(`SELECT id FROM ${table} WHERE ${where} LIMIT 1`,values);return rows[0]?{table,id:Number(rows[0].id)}:null;}
  private async exists(table:string,column:string,value:unknown,extra="1=1"){const allowed=allowedLookups[table];if(!allowed?.has(column))throw new Error("Consulta de validación no permitida.");const rows=await this.database.query<RowDataPacket[]>(`SELECT 1 FROM ${table} WHERE ${column}=? AND ${extra} LIMIT 1`,[value]);return Boolean(rows[0]);}
  private async findId(table:string,column:string,value:unknown){const allowed=allowedLookups[table];if(!allowed?.has(column))throw new Error("Consulta de validación no permitida.");const rows=await this.database.query<(RowDataPacket&{id:number})[]>(`SELECT id FROM ${table} WHERE ${column}=? LIMIT 1`,[value]);return rows[0]?.id?Number(rows[0].id):null;}
  private async persistIssue(connection:PoolConnection,batchId:number,row:StagingRow,issue:Issue){if(issue.kind==="error")await connection.query("INSERT INTO migration_validation_errors (batch_id,staging_row_id,`row_number`,severity,error_code,column_name,message,masked_value) VALUES (?,?,?,'ERROR',?,?,?,?)",[batchId,row.id,row.row_number,issue.code,issue.field,issue.message,maskMigrationValue(issue.field??"",issue.value)]);else await connection.query("INSERT INTO migration_conflicts (batch_id,staging_row_id,`row_number`,conflict_type,field_name,source_value_masked,candidate_target_type,candidate_target_id) VALUES (?,?,?,?,?,?,?,?)",[batchId,row.id,row.row_number,issue.type??"MAPPING_REQUIRED",issue.field,maskMigrationValue(issue.field??"",issue.value),issue.candidateType??null,issue.candidateId??null]);}
  private async count(table:string,batchId:number,condition="1=1"){const allowed=new Set(["migration_conflicts","migration_validation_errors","migration_staging_rows"]);if(!allowed.has(table))throw new Error("Conteo no permitido.");const rows=await this.database.query<(RowDataPacket&{total:number})[]>(`SELECT COUNT(*) total FROM ${table} WHERE batch_id=? AND ${condition}`,[batchId]);return rows[0]?.total??0;}
  private async countOn(connection:PoolConnection,table:string,batchId:number,condition:string){const [rows]=await connection.query<(RowDataPacket&{total:number})[]>(`SELECT COUNT(*) total FROM ${table} WHERE batch_id=? AND ${condition}`,[batchId]);return rows[0]?.total??0;}
  private async pageTable(table:"migration_validation_errors"|"migration_conflicts",batchId:number,page:number,pageSize:number,order:string){const total=await this.count(table,batchId);const rows=await this.database.query<RowDataPacket[]>(`SELECT * FROM ${table} WHERE batch_id=? ORDER BY ${order} LIMIT ? OFFSET ?`,[batchId,pageSize,(page-1)*pageSize]);return {rows,total};}
  private async execution(connection:PoolConnection,batchId:number,action:string,outcome:string,message:string,actor:string|null,requestId:string|null,metadata?:unknown){await connection.query("INSERT INTO migration_execution_logs (batch_id,action,outcome,message,metadata,actor_user_id,request_id) VALUES (?,?,?,?,?,?,?)",[batchId,action,outcome,message,metadata===undefined?null:JSON.stringify(metadata),actor,requestId]);}
  private async log(batchId:number,action:string,outcome:string,message:string,actor:string|null,requestId:string|null){await this.database.query("INSERT INTO migration_execution_logs (batch_id,action,outcome,message,actor_user_id,request_id) VALUES (?,?,?,?,?,?)",[batchId,action,outcome,message,actor,requestId]);}
  private async writeReviewReports(batchId:number){const batch=await this.requireBatch(batchId);const folder=this.safePath(`${batch.public_reference}/reports`);await mkdir(folder,{recursive:true,mode:0o700});const errors=await this.database.query<RowDataPacket[]>("SELECT `row_number`,error_code,column_name,message,masked_value FROM migration_validation_errors WHERE batch_id=? ORDER BY `row_number`,id",[batch.id]);const conflicts=await this.database.query<RowDataPacket[]>("SELECT `row_number`,conflict_type,field_name,source_value_masked,status FROM migration_conflicts WHERE batch_id=? ORDER BY `row_number`,id",[batch.id]);await writeFile(resolve(folder,"errors.csv"),this.rowsCsv(errors),{mode:0o600});await writeFile(resolve(folder,"conflicts.csv"),this.rowsCsv(conflicts),{mode:0o600});}
  private rowsCsv(rows:RowDataPacket[]){if(!rows[0])return "\uFEFF";const headers=Object.keys(rows[0]);return `\uFEFF${headers.map(csvCell).join(",")}\r\n${rows.map((row)=>headers.map((header)=>csvCell(row[header])).join(",")).join("\r\n")}\r\n`;}
  private async createBackupManifest(batch:BatchRow){const tables=await this.database.query<(RowDataPacket&{table_name:string;table_rows:number})[]>("SELECT TABLE_NAME table_name,TABLE_ROWS table_rows FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_TYPE='BASE TABLE' ORDER BY TABLE_NAME");const file=await this.database.query<(RowDataPacket&{checksum_sha256:string})[]>("SELECT checksum_sha256 FROM migration_files WHERE batch_id=?",[batch.id]);const payload=JSON.stringify({kind:"PRE_IMPORT_MANIFEST",batch:batch.public_reference,sourceSystem:batch.source_system,entity:batch.entity_type,sourceChecksum:file[0]?.checksum_sha256,createdAt:new Date().toISOString(),note:"La importación es append-only y no sobrescribe filas operativas.",tableCounts:tables},null,2);const checksum=createHash("sha256").update(payload).digest("hex");const key=`${batch.public_reference}/backup/pre-import-${checksum.slice(0,16)}.json`;const path=this.safePath(key);await mkdir(resolve(path,".."),{recursive:true,mode:0o700});await writeFile(path,payload,{mode:0o600});return {reference:`${key}#sha256=${checksum}`};}
}

const allowedLookups:Record<string,Set<string>>={users:new Set(["email"]),sites:new Set(["code"]),devices:new Set(["device_uuid"]),cash_sessions:new Set(["id"]),institutional_rule_versions:new Set(["id"]),infraction_types:new Set(["code"]),payment_methods:new Set(["code"])};
function state(action:string,status:string){return new HttpError({code:"MIGRATION_BATCH_STATE_INVALID",message:`No se puede ${action} un lote en estado ${status}.`,statusCode:409});}
function conflict(type:string,field:string,message:string,value:unknown,candidateType?:string,candidateId?:number):Issue{return {kind:"conflict",type,code:`MIGRATION_${type}`,field,message,value,...(candidateType===undefined?{}:{candidateType}),...(candidateId===undefined?{}:{candidateId})};}
