import { Router } from "express";
import type { PoolConnection, ResultSetHeader, RowDataPacket } from "mysql2/promise";
import { z } from "zod";
import type { AppContainer } from "../../../bootstrap/container.js";
import { authenticate } from "../../../shared/http/authenticate.js";
import { authorize } from "../../../shared/http/authorize.js";
import { HttpError } from "../../../shared/http/HttpError.js";
import { getRequestId } from "../../../shared/http/request-context.js";
import { isDuplicateKey, recordOperation } from "../../../shared/http/operations.js";

const strongPassword = z.string().min(12).max(128).regex(/[a-z]/).regex(/[A-Z]/).regex(/\d/).regex(/[^a-zA-Z0-9]/);
const userCreate = z.object({
  username: z.string().trim().min(3).max(50), email: z.email().max(191).nullable().optional(),
  password: strongPassword, firstName: z.string().trim().min(1).max(100), lastName: z.string().trim().min(1).max(100),
  phone: z.string().trim().max(30).nullable().optional(), employeeCode: z.string().trim().max(50).nullable().optional(),
  siteId: z.coerce.number().int().positive().nullable().optional(), departmentId: z.coerce.number().int().positive().nullable().optional(),
  positionId: z.coerce.number().int().positive().nullable().optional(), roleIds: z.array(z.coerce.number().int().positive()).max(20).default([]),
});
const userUpdate = userCreate.omit({ password: true, roleIds: true }).partial().refine((value) => Object.keys(value).length > 0);
const rolesInput = z.object({ roleIds: z.array(z.coerce.number().int().positive()).max(20) });
const roleInput = z.object({ code: z.string().trim().min(2).max(50), name: z.string().trim().min(2).max(100), description: z.string().trim().max(300).nullable().optional() });
const roleUpdate = roleInput.partial().refine((value) => Object.keys(value).length > 0);
const permissionInput = z.object({ permissionIds: z.array(z.coerce.number().int().positive()).max(200) });
const listQuery = z.object({ search: z.string().trim().max(150).default(""), status: z.enum(["ACTIVE", "DISABLED", "LOCKED"]).optional(), page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(20) });

type UserRow = RowDataPacket & { id: number | string; username: string; email: string | null; first_name: string; last_name: string; phone: string | null; employee_code: string | null; site_id: number | string | null; department_id: number | string | null; department_name: string | null; position_id: number | string | null; status: string; must_change_password: number; last_login_at: Date | null; created_at: Date; updated_at: Date; role_codes: string | null; role_names: string | null };

function userView(row: UserRow) {
  const codes = row.role_codes?.split(",") ?? []; const names = row.role_names?.split(",") ?? [];
  return { id: String(row.id), username: row.username, email: row.email, firstName: row.first_name, lastName: row.last_name, phone: row.phone, employeeCode: row.employee_code, siteId: row.site_id === null ? null : String(row.site_id), departmentId: row.department_id === null ? null : String(row.department_id), departmentName: row.department_name, positionId: row.position_id === null ? null : String(row.position_id), status: row.status, mustChangePassword: Boolean(row.must_change_password), lastLoginAt: row.last_login_at, createdAt: row.created_at, updatedAt: row.updated_at, roles: codes.map((code, index) => ({ code, name: names[index] ?? code })) };
}

async function activeAdminCount(connection: PoolConnection): Promise<number> {
  const [rows] = await connection.query<(RowDataPacket & { total: number })[]>(`SELECT COUNT(DISTINCT u.id) total FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE u.status='ACTIVE' AND r.code='ADMIN' AND r.is_active=1 AND (ur.expires_at IS NULL OR ur.expires_at > UTC_TIMESTAMP(3))`);
  return rows[0]?.total ?? 0;
}

export function createAdministrationRouter(container: AppContainer): Router {
  const router = Router(); router.use(authenticate(container.authRepository, container.env));
  router.get("/users", authorize("users.read", container.auditRepository), async (request, response, next) => {
    try { const query = listQuery.parse(request.query); const clauses: string[] = []; const values: unknown[] = []; if (query.status) { clauses.push("u.status=?"); values.push(query.status); } if (query.search) { clauses.push("(u.username LIKE ? OR u.email LIKE ? OR u.first_name LIKE ? OR u.last_name LIKE ? OR u.employee_code LIKE ?)"); const like=`%${query.search}%`; values.push(like,like,like,like,like); } const where=clauses.length?`WHERE ${clauses.join(" AND ")}`:""; const counts=await container.database.query<(RowDataPacket&{total:number})[]>(`SELECT COUNT(*) total FROM users u ${where}`,values); const rows=await container.database.query<UserRow[]>(`SELECT u.*,d.name department_name,GROUP_CONCAT(DISTINCT r.code ORDER BY r.code) role_codes,GROUP_CONCAT(DISTINCT r.name ORDER BY r.code) role_names FROM users u LEFT JOIN departments d ON d.id=u.department_id LEFT JOIN user_roles ur ON ur.user_id=u.id AND (ur.expires_at IS NULL OR ur.expires_at>UTC_TIMESTAMP(3)) LEFT JOIN roles r ON r.id=ur.role_id ${where} GROUP BY u.id ORDER BY u.last_name,u.first_name LIMIT ? OFFSET ?`,[...values,query.pageSize,(query.page-1)*query.pageSize]); response.json({data:rows.map(userView),meta:{page:query.page,pageSize:query.pageSize,total:counts[0]?.total??0,requestId:getRequestId()}}); } catch(error){next(error);} 
  });
  router.get("/users/:id", authorize("users.read", container.auditRepository), async (request,response,next)=>{try{const id=z.coerce.number().int().positive().parse(request.params["id"]);const rows=await container.database.query<UserRow[]>(`SELECT u.*,d.name department_name,GROUP_CONCAT(DISTINCT r.code ORDER BY r.code) role_codes,GROUP_CONCAT(DISTINCT r.name ORDER BY r.code) role_names FROM users u LEFT JOIN departments d ON d.id=u.department_id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id WHERE u.id=? GROUP BY u.id`,[id]);if(!rows[0])throw new HttpError({code:"USER_NOT_FOUND",message:"Usuario no encontrado.",statusCode:404});response.json({data:userView(rows[0]),meta:{requestId:getRequestId()}});}catch(error){next(error);}});
  router.post("/users", authorize("users.create", container.auditRepository), async (request,response,next)=>{try{const input=userCreate.parse(request.body);const hash=await container.passwordHasher.hash(input.password);const id=await container.database.withTransaction(async(connection)=>{const [result]=await connection.query<ResultSetHeader>(`INSERT INTO users (username,email,password_hash,first_name,last_name,phone,employee_code,site_id,department_id,position_id) VALUES (?,?,?,?,?,?,?,?,?,?)`,[input.username,input.email??null,hash,input.firstName,input.lastName,input.phone??null,input.employeeCode??null,input.siteId??null,input.departmentId??null,input.positionId??null]);for(const roleId of input.roleIds)await connection.query("INSERT INTO user_roles (user_id,role_id,assigned_by_user_id) VALUES (?,?,?)",[result.insertId,roleId,request.auth?.user.id??null]);return String(result.insertId);});await recordOperation(container,request,{action:"USER_CREATED",module:"users",entityType:"user",entityId:id});response.status(201).json({data:{id},meta:{requestId:getRequestId()}});}catch(error){if(isDuplicateKey(error))return next(new HttpError({code:"USER_DUPLICATE",message:"El usuario, correo o código de empleado ya existe.",statusCode:409}));next(error);}});
  router.patch("/users/:id", authorize("users.update", container.auditRepository), async(request,response,next)=>{try{const id=z.coerce.number().int().positive().parse(request.params["id"]);const input=userUpdate.parse(request.body);const columns:string[]=[];const values:unknown[]=[];const map={username:"username",email:"email",firstName:"first_name",lastName:"last_name",phone:"phone",employeeCode:"employee_code",siteId:"site_id",departmentId:"department_id",positionId:"position_id"} as const;for(const [key,column] of Object.entries(map) as [keyof typeof map,string][])if(input[key]!==undefined){columns.push(`${column}=?`);values.push(input[key]);}const result=await container.database.query<ResultSetHeader>(`UPDATE users SET ${columns.join(",")} WHERE id=?`,[...values,id]);if(!result.affectedRows)throw new HttpError({code:"USER_NOT_FOUND",message:"Usuario no encontrado.",statusCode:404});await recordOperation(container,request,{action:"USER_UPDATED",module:"users",entityType:"user",entityId:String(id)});response.sendStatus(204);}catch(error){if(isDuplicateKey(error))return next(new HttpError({code:"USER_DUPLICATE",message:"El usuario, correo o código de empleado ya existe.",statusCode:409}));next(error);}});
  for(const [path,status,action] of [["activate","ACTIVE","USER_ACTIVATED"],["deactivate","DISABLED","USER_DEACTIVATED"]] as const)router.post(`/users/:id/${path}`,authorize("users.change_status",container.auditRepository),async(request,response,next)=>{try{const id=z.coerce.number().int().positive().parse(request.params["id"]);await container.database.withTransaction(async(connection)=>{const [rows]=await connection.query<(RowDataPacket&{admin:number})[]>(`SELECT EXISTS(SELECT 1 FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=? AND r.code='ADMIN') admin FROM users WHERE id=? FOR UPDATE`,[id,id]);if(!rows[0])throw new HttpError({code:"USER_NOT_FOUND",message:"Usuario no encontrado.",statusCode:404});if(status==="DISABLED"&&rows[0].admin===1&&(await activeAdminCount(connection))<=1)throw new HttpError({code:"LAST_ADMIN_REQUIRED",message:"No se puede desactivar al último ADMIN activo.",statusCode:409});await connection.query("UPDATE users SET status=?,session_version=session_version+IF(?='DISABLED',1,0) WHERE id=?",[status,status,id]);if(status==="DISABLED")await connection.query("UPDATE user_sessions SET revoked_at=COALESCE(revoked_at,UTC_TIMESTAMP(3)),revoked_by_user_id=?,revoke_reason='Usuario desactivado' WHERE user_id=? AND revoked_at IS NULL",[request.auth?.user.id??null,id]);});await recordOperation(container,request,{action,module:"users",entityType:"user",entityId:String(id)});response.sendStatus(204);}catch(error){next(error);}});
  router.put("/users/:id/roles",authorize("users.assign_roles",container.auditRepository),async(request,response,next)=>{try{const id=z.coerce.number().int().positive().parse(request.params["id"]);const {roleIds}=rolesInput.parse(request.body);await container.database.withTransaction(async(connection)=>{const [users]=await connection.query<RowDataPacket[]>("SELECT id,status FROM users WHERE id=? FOR UPDATE",[id]);if(!users[0])throw new HttpError({code:"USER_NOT_FOUND",message:"Usuario no encontrado.",statusCode:404});const [adminRole]=await connection.query<(RowDataPacket&{id:number|string})[]>("SELECT id FROM roles WHERE code='ADMIN'",[]);const adminId=String(adminRole[0]?.id??"");const [current]=await connection.query<(RowDataPacket&{role_id:number|string})[]>("SELECT role_id FROM user_roles WHERE user_id=?",[id]);const removesAdmin=current.some(row=>String(row.role_id)===adminId)&&!roleIds.some(roleId=>String(roleId)===adminId);if(removesAdmin&&users[0]["status"]==="ACTIVE"&&(await activeAdminCount(connection))<=1)throw new HttpError({code:"LAST_ADMIN_REQUIRED",message:"No se puede retirar el rol al último ADMIN activo.",statusCode:409});await connection.query("DELETE FROM user_roles WHERE user_id=?",[id]);for(const roleId of roleIds)await connection.query("INSERT INTO user_roles (user_id,role_id,assigned_by_user_id) VALUES (?,?,?)",[id,roleId,request.auth?.user.id??null]);});await recordOperation(container,request,{action:"USER_ROLES_REPLACED",module:"users",entityType:"user",entityId:String(id)});response.sendStatus(204);}catch(error){next(error);}});
  router.post("/users/:id/revoke-sessions",authorize("users.change_status",container.auditRepository),async(request,response,next)=>{try{const id=z.coerce.number().int().positive().parse(request.params["id"]);const rows=await container.database.query<RowDataPacket[]>("SELECT id FROM users WHERE id=?",[id]);if(!rows[0])throw new HttpError({code:"USER_NOT_FOUND",message:"Usuario no encontrado.",statusCode:404});await container.authRepository.revokeAllSessions(String(id),"Revocación administrativa");await recordOperation(container,request,{action:"USER_SESSIONS_REVOKED",module:"users",entityType:"user",entityId:String(id)});response.sendStatus(204);}catch(error){next(error);}});

  router.get("/roles",authorize("roles.read",container.auditRepository),async(_request,response,next)=>{try{const rows=await container.database.query<RowDataPacket[]>(`SELECT r.id,r.code,r.name,r.description,r.is_system,r.is_active,COUNT(DISTINCT rp.permission_id) permission_count,COUNT(DISTINCT ur.user_id) user_count,GROUP_CONCAT(DISTINCT rp.permission_id ORDER BY rp.permission_id) permission_ids FROM roles r LEFT JOIN role_permissions rp ON rp.role_id=r.id LEFT JOIN user_roles ur ON ur.role_id=r.id GROUP BY r.id ORDER BY r.name`);const permissions=await container.database.query<RowDataPacket[]>("SELECT id,code,module,action,description,is_active FROM permissions ORDER BY module,code");response.json({data:{roles:rows,permissions},meta:{requestId:getRequestId()}});}catch(error){next(error);}});
  router.post("/roles",authorize("roles.manage",container.auditRepository),async(request,response,next)=>{try{const input=roleInput.parse(request.body);const result=await container.database.query<ResultSetHeader>("INSERT INTO roles (code,name,description,is_system,is_active) VALUES (?,?,?,0,1)",[input.code.toUpperCase(),input.name,input.description??null]);await recordOperation(container,request,{action:"ROLE_CREATED",module:"roles",entityType:"role",entityId:String(result.insertId)});response.status(201).json({data:{id:String(result.insertId)},meta:{requestId:getRequestId()}});}catch(error){if(isDuplicateKey(error))return next(new HttpError({code:"ROLE_DUPLICATE",message:"El rol ya existe.",statusCode:409}));next(error);}});
  router.patch("/roles/:id",authorize("roles.manage",container.auditRepository),async(request,response,next)=>{try{const id=z.coerce.number().int().positive().parse(request.params["id"]);const input=roleUpdate.parse(request.body);const cols:string[]=[];const vals:unknown[]=[];for(const [key,col] of [["code","code"],["name","name"],["description","description"]] as const)if(input[key]!==undefined){cols.push(`${col}=?`);vals.push(key==="code"?input[key].toUpperCase():input[key]);}const result=await container.database.query<ResultSetHeader>(`UPDATE roles SET ${cols.join(",")} WHERE id=?`,[...vals,id]);if(!result.affectedRows)throw new HttpError({code:"ROLE_NOT_FOUND",message:"Rol no encontrado.",statusCode:404});await recordOperation(container,request,{action:"ROLE_UPDATED",module:"roles",entityType:"role",entityId:String(id)});response.sendStatus(204);}catch(error){next(error);}});
  router.put("/roles/:id/permissions",authorize("roles.manage",container.auditRepository),async(request,response,next)=>{try{const id=z.coerce.number().int().positive().parse(request.params["id"]);const {permissionIds}=permissionInput.parse(request.body);await container.database.withTransaction(async(connection)=>{const [roles]=await connection.query<RowDataPacket[]>("SELECT id FROM roles WHERE id=? FOR UPDATE",[id]);if(!roles[0])throw new HttpError({code:"ROLE_NOT_FOUND",message:"Rol no encontrado.",statusCode:404});await connection.query("DELETE FROM role_permissions WHERE role_id=?",[id]);for(const permissionId of permissionIds)await connection.query("INSERT INTO role_permissions (role_id,permission_id) VALUES (?,?)",[id,permissionId]);});await recordOperation(container,request,{action:"ROLE_PERMISSIONS_REPLACED",module:"roles",entityType:"role",entityId:String(id)});response.sendStatus(204);}catch(error){next(error);}});
  return router;
}
