"use client";

import { useEffect, useMemo, useState } from "react";
import { Alert, Box, CircularProgress, FormControl, Grid, InputLabel, MenuItem, Paper, Select, Stack, TextField, Typography } from "@mui/material";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader, StatCard } from "@/src/components/common";
import { analyticsApi, type DashboardData, type Metric } from "@/src/modules/analytics/api/analyticsApi";

const today = new Date(); const initialTo = today.toISOString().slice(0,10); const fromDate = new Date(today); fromDate.setDate(fromDate.getDate()-29); const initialFrom = fromDate.toISOString().slice(0,10);

export default function DashboardPage() {
  const [from,setFrom]=useState(initialFrom); const [to,setTo]=useState(initialTo); const [departmentId,setDepartmentId]=useState(""); const [data,setData]=useState<DashboardData|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
  useEffect(()=>{ let active=true; setLoading(true); setError(""); const params=new URLSearchParams({from,to}); if(departmentId) params.set("departmentId",departmentId); void analyticsApi.dashboard(params).then((result)=>{if(active)setData(result.data);}).catch((reason:unknown)=>{if(active)setError(reason instanceof Error?reason.message:"No se pudo cargar el dashboard.");}).finally(()=>{if(active)setLoading(false);}); return()=>{active=false;}; },[from,to,departmentId]);
  const count=(rows:Metric[],label?:string)=>rows.filter((row)=>!label||row.label===label).reduce((total,row)=>total+Number(row.count),0);
  const pendingBalance=useMemo(()=>data?.kpis.orders.reduce((total,row)=>addDecimal(total,row.amount??"0.00"),"0.00")??"0.00",[data]);
  if(!data&&loading) return <Box className="module-page" sx={{display:"grid",placeItems:"center",minHeight:360}}><CircularProgress /></Box>;
  return <Box className="module-page"><PageHeader eyebrow="Control institucional" title="Dashboard administrativo" description="Indicadores calculados directamente en MySQL; los filtros se aplican a todas las métricas y gráficas." />
    <Paper variant="outlined" className="dashboard-filter-bar"><TextField type="date" label="Desde" value={from} onChange={(event)=>setFrom(event.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField type="date" label="Hasta" value={to} onChange={(event)=>setTo(event.target.value)} slotProps={{inputLabel:{shrink:true}}}/><FormControl><InputLabel>Dependencia</InputLabel><Select label="Dependencia" value={departmentId} onChange={(event)=>setDepartmentId(event.target.value)}><MenuItem value="">Todas</MenuItem>{data?.departments.map((item)=><MenuItem key={item.id} value={String(item.id)}>{item.name}</MenuItem>)}</Select></FormControl></Paper>
    {error&&<Alert severity="error">{error}</Alert>}{loading&&<CircularProgress size={22}/>} {data&&<><Grid container spacing={2} className="stats-grid"><MetricCard label="Infracciones" value={String(count(data.kpis.infractions))} helper={`${count(data.kpis.infractions,"PENDIENTE_VALIDACION")} pendientes · ${count(data.kpis.infractions,"VALIDADA")} validadas · ${count(data.kpis.infractions,"RECHAZADA")} rechazadas`} /><MetricCard label="Monto original" value={currency(sum(data.kpis.infractions))} helper="Importe de boletas del período"/><MetricCard label="Recaudación neta" value={currency(data.kpis.payments.amount??"0.00")} helper={`${data.kpis.payments.count} pagos vigentes`} tone="success"/><MetricCard label="Saldo de órdenes" value={currency(pendingBalance)} helper={`${count(data.kpis.orders)} órdenes emitidas`} tone="warning"/><MetricCard label="Reversos" value={currency(data.kpis.reversals.amount??"0.00")} helper={`${data.kpis.reversals.count} operaciones`} tone="warning"/><MetricCard label="Ajustes aprobados" value={currency(sum(data.kpis.adjustments))} helper={`${count(data.kpis.adjustments)} descuentos, exoneraciones, recargos o correcciones`}/><MetricCard label="Cajas" value={String(count(data.kpis.cash))} helper={`${count(data.kpis.cash,"OPEN")} abiertas · ${count(data.kpis.cash,"CLOSED")} cerradas · diferencia ${currency(sum(data.kpis.cash))}`}/><MetricCard label="Impugnaciones" value={String(count(data.kpis.appeals))} helper={`${data.kpis.appeals.filter((row)=>String(row.label).startsWith("RESUELTA_")).reduce((total,row)=>total+Number(row.count),0)} resueltas`}/><MetricCard label="Solvencias" value={String(count(data.kpis.solvencies))} helper={`${count(data.kpis.solvencies,"VALID")} emitidas · ${count(data.kpis.solvencies,"OBSERVED")} observadas · ${count(data.kpis.solvencies,"REVOKED")} revocadas`} tone="success"/></Grid>
    <Grid container spacing={2} className="dashboard-charts"><Chart title="Recaudación diaria"><BarChart data={data.charts.collectionDaily}><CartesianGrid stroke="#E6EAE2" vertical={false}/><XAxis dataKey="label"/><YAxis/><Tooltip formatter={(value)=>currency(String(value))}/><Bar dataKey="amount" fill="#5A6A3D" radius={[8,8,0,0]}/></BarChart></Chart><Chart title="Recaudación mensual"><BarChart data={data.charts.collectionMonthly}><CartesianGrid stroke="#E6EAE2" vertical={false}/><XAxis dataKey="label"/><YAxis/><Tooltip formatter={(value)=>currency(String(value))}/><Bar dataKey="amount" fill="#C7942F" radius={[8,8,0,0]}/></BarChart></Chart><Chart title="Infracciones por estado"><PieChart><Pie data={data.kpis.infractions} dataKey="count" nameKey="label" outerRadius={92} fill="#66794a" label/><Tooltip/></PieChart></Chart><Chart title="Recaudación por método"><PieChart><Pie data={data.charts.byMethod} dataKey="amount" nameKey="label" outerRadius={92} fill="#C7942F" label/><Tooltip formatter={(value)=>currency(String(value))}/></PieChart></Chart><Chart title="Emitidas frente a pagos"><LineChart data={data.charts.issuedVsPaid}><CartesianGrid stroke="#E6EAE2" vertical={false}/><XAxis dataKey="label"/><YAxis/><Tooltip/><Legend/><Line dataKey="issued" name="Emitidas" stroke="#5A6A3D"/><Line dataKey="paid" name="Pagos" stroke="#C7942F"/></LineChart></Chart><Chart title="Tendencia de impugnaciones"><LineChart data={data.charts.appealTrend}><CartesianGrid stroke="#E6EAE2" vertical={false}/><XAxis dataKey="label"/><YAxis/><Tooltip/><Legend/><Line dataKey="count" name="Presentadas" stroke="#7994A2"/><Line dataKey="resolved" name="Resueltas" stroke="#5A6A3D"/></LineChart></Chart><Chart title="Antigüedad de saldos"><BarChart data={data.charts.aging}><CartesianGrid stroke="#E6EAE2" vertical={false}/><XAxis dataKey="label"/><YAxis/><Tooltip formatter={(value)=>currency(String(value))}/><Bar dataKey="amount" fill="#B06158" radius={[8,8,0,0]}/></BarChart></Chart><Chart title="Por tipo de infracción"><BarChart data={data.charts.byType} layout="vertical"><CartesianGrid stroke="#E6EAE2" horizontal={false}/><XAxis type="number"/><YAxis type="category" dataKey="label" width={120}/><Tooltip/><Bar dataKey="count" fill="#7994A2"/></BarChart></Chart><Chart title="Por agente"><BarChart data={data.charts.byAgent}><CartesianGrid stroke="#E6EAE2" vertical={false}/><XAxis dataKey="label"/><YAxis/><Tooltip/><Bar dataKey="count" fill="#5A6A3D"/></BarChart></Chart><Chart title="Por ubicación"><BarChart data={data.charts.byLocation} layout="vertical"><CartesianGrid stroke="#E6EAE2" horizontal={false}/><XAxis type="number"/><YAxis type="category" dataKey="label" width={140}/><Tooltip/><Bar dataKey="count" fill="#B06158"/></BarChart></Chart></Grid></>}</Box>;
}

function MetricCard(props:{label:string;value:string;helper:string;tone?:"primary"|"warning"|"success"}){return <Grid size={{xs:12,sm:6,xl:3}}><StatCard {...props}/></Grid>}
function Chart({title,children}:{title:string;children:React.ReactElement}){return <Grid size={{xs:12,lg:6}}><Paper variant="outlined" className="chart-card"><Stack><Typography className="overline">Datos reales</Typography><Typography variant="h6">{title}</Typography></Stack><ResponsiveContainer width="100%" height={280}>{children}</ResponsiveContainer></Paper></Grid>}
function currency(value:string){return new Intl.NumberFormat("es-GT",{style:"currency",currency:"GTQ"}).format(Number(value));}
function sum(rows:Metric[]){return rows.reduce((total,row)=>addDecimal(total,row.amount??"0.00"),"0.00");}
export function addDecimal(left:string,right:string){const cents=(value:string)=>{const negative=value.startsWith("-");const normalized=negative?value.slice(1):value;const [whole="0",fraction=""]=normalized.split(".");const amount=BigInt(whole)*100n+BigInt(fraction.padEnd(2,"0").slice(0,2));return negative?-amount:amount;};const result=cents(left)+cents(right);const negative=result<0n;const absolute=negative?-result:result;return `${negative?"-":""}${absolute/100n}.${String(absolute%100n).padStart(2,"0")}`;}
