import { randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { RowDataPacket } from "mysql2/promise";
import { describe, expect, it } from "vitest";
import { createDatabasePool } from "../../src/config/database.js";
import { loadEnv } from "../../src/config/env.js";
import { HistoricalMigrationService } from "../../src/modules/historical-migrations/application/HistoricalMigrationService.js";
import { MySqlConnection } from "../../src/shared/infrastructure/mysql/MySqlConnection.js";

const enabled=process.env["RUN_MYSQL_INTEGRATION"]==="true";

describe.skipIf(!enabled)("migración histórica MySQL",()=>{
  it("valida, importa, reintenta, bloquea dependencias, revierte y no deja residuos operativos",async()=>{
    const env=loadEnv();const pool=createDatabasePool(env);const database=new MySqlConnection(pool);const directory=await mkdtemp(join(tmpdir(),"pmt-historical-test-"));const marker=randomUUID().replaceAll("-","").toUpperCase();const source=`TEST_${marker}`;const batchIds:number[]=[];
    try{
      const admins=await database.query<(RowDataPacket&{id:string})[]>("SELECT u.id FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE r.code='ADMIN' AND u.status='ACTIVE' LIMIT 1");const actor=admins[0]?.id;expect(actor).toBeDefined();if(!actor)throw new Error("Administrador requerido");const service=new HistoricalMigrationService(database,directory,1_000_000,1);
      const first=await service.upload({content:citizensCsv(marker,["A"]),originalName:`${marker}.csv`,mimeType:"text/csv",sourceSystem:source,entity:"citizens",actorUserId:actor});batchIds.push(first.batch.id);const validated=await service.validate(first.batch.id,actor,randomUUID());expect(validated.batch.status).toBe("VALIDATED");expect(validated.errors).toBe(0);expect((await service.approve(first.batch.id,actor,randomUUID())).batch.status).toBe("READY");
      const confirmation=`IMPORTAR ${first.batch.public_reference}`;const imported=await service.commit(first.batch.id,actor,confirmation,randomUUID());expect(imported.detail.batch.status).toBe("COMPLETED");expect((await service.commit(first.batch.id,actor,confirmation,randomUUID())).idempotentReplay).toBe(true);expect(await count(database,"SELECT COUNT(*) total FROM citizens WHERE identification_number=?",[`TEST-${marker}-A`])).toBe(1);
      await database.query("INSERT INTO driver_licenses (citizen_id,license_number,license_number_normalized,license_type,status) SELECT id,?,?,?,'ACTIVE' FROM citizens WHERE identification_number=?",[`LIC-${marker}`,`LIC${marker}`,"A",`TEST-${marker}-A`]);await expect(service.revert(first.batch.id,actor,`REVERTIR ${first.batch.public_reference}`,randomUUID())).rejects.toMatchObject({code:"MIGRATION_REVERT_UNSAFE"});await database.query("DELETE FROM driver_licenses WHERE license_number_normalized=?",[`LIC${marker}`]);const reverted=await service.revert(first.batch.id,actor,`REVERTIR ${first.batch.public_reference}`,randomUUID());expect(reverted.detail.batch.status).toBe("REVERTED");expect((await service.revert(first.batch.id,actor,`REVERTIR ${first.batch.public_reference}`,randomUUID())).idempotentReplay).toBe(true);expect(await count(database,"SELECT COUNT(*) total FROM citizens WHERE identification_number=?",[`TEST-${marker}-A`])).toBe(0);
      const second=await service.upload({content:citizensCsv(marker,["B","C"]),originalName:`${marker}-rollback.csv`,mimeType:"text/csv",sourceSystem:source,entity:"citizens",actorUserId:actor});batchIds.push(second.batch.id);await service.validate(second.batch.id,actor,randomUUID());const rows=await database.query<(RowDataPacket&{id:number;normalized_data:string|Record<string,string>})[]>("SELECT id,normalized_data FROM migration_staging_rows WHERE batch_id=? ORDER BY `row_number`",[second.batch.id]);const firstData=asRecord(rows[0]?.normalized_data);const secondData=asRecord(rows[1]?.normalized_data);const duplicateNumber=firstData["identification_number"];const duplicateNormalized=firstData["identification_normalized"];if(!duplicateNumber||!duplicateNormalized)throw new Error("Identificación sintética ausente");secondData["identification_number"]=duplicateNumber;secondData["identification_normalized"]=duplicateNormalized;await database.query("UPDATE migration_staging_rows SET normalized_data=? WHERE id=?",[JSON.stringify(secondData),rows[1]?.id]);await expect(service.commit(second.batch.id,actor,`IMPORTAR ${second.batch.public_reference}`,randomUUID())).rejects.toBeDefined();expect(await count(database,"SELECT COUNT(*) total FROM citizens WHERE identification_number LIKE ?",[`TEST-${marker}-%`])).toBe(0);expect((await service.detail(second.batch.id)).batch.status).toBe("FAILED");
    }finally{for(const batchId of batchIds.reverse()){await database.query("DELETE FROM legacy_source_references WHERE imported_by_batch_id=?",[batchId]);await database.query("DELETE FROM migration_execution_logs WHERE batch_id=?",[batchId]);await database.query("DELETE FROM migration_conflicts WHERE batch_id=?",[batchId]);await database.query("DELETE FROM migration_validation_errors WHERE batch_id=?",[batchId]);await database.query("DELETE FROM migration_staging_rows WHERE batch_id=?",[batchId]);await database.query("DELETE FROM migration_files WHERE batch_id=?",[batchId]);await database.query("DELETE FROM migration_batches WHERE id=?",[batchId]);}await database.close();await rm(directory,{recursive:true,force:true});}
  });
});

function citizensCsv(marker:string,suffixes:string[]):Buffer{const header="legacy_id,identification_type,identification_number,nit,first_names,last_names,address,phone,email,status";return Buffer.from(`${header}\n${suffixes.map((suffix)=>`C-${marker}-${suffix},OTHER,TEST-${marker}-${suffix},,Synthetic${suffix},Migration,,,,ACTIVE`).join("\n")}\n`);}
function asRecord(value:string|Record<string,string>|undefined):Record<string,string>{if(!value)throw new Error("Datos normalizados ausentes");return typeof value==="string"?JSON.parse(value) as Record<string,string>:value;}
async function count(database:MySqlConnection,sql:string,values:unknown[]){const rows=await database.query<(RowDataPacket&{total:number})[]>(sql,values);return rows[0]?.total??0;}
