import { createTheme } from "@mui/material/styles";

export const theme = createTheme({
  palette: {
    mode: "light",
    primary: { main: "#5A6A3D", dark: "#35452B", light: "#A3B18A", contrastText: "#FFFFFF" },
    secondary: { main: "#D5A739" },
    background: { default: "#F5F7F3", paper: "#FFFFFF" },
    text: { primary: "#283126", secondary: "#667064" },
    divider: "#DDE3D8",
    success: { main: "#3F7654" },
    warning: { main: "#A76A17" },
    error: { main: "#A9463D" },
    info: { main: "#386F8E" },
  },
  typography: {
    fontFamily: 'Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    h1: { fontWeight: 780, letterSpacing: "-0.045em" },
    h2: { fontWeight: 760, letterSpacing: "-0.035em" },
    h3: { fontWeight: 740, letterSpacing: "-0.025em" },
    h4: { fontWeight: 720, letterSpacing: "-0.02em" },
    h5: { fontWeight: 700, letterSpacing: "-0.015em" },
    h6: { fontWeight: 700, letterSpacing: "-0.01em" },
    body1: { lineHeight: 1.6 },
    body2: { lineHeight: 1.55 },
    button: { textTransform: "none", fontWeight: 700 },
  },
  shape: { borderRadius: 14 },
  components: {
    MuiButton: { defaultProps: { disableElevation: true }, styleOverrides: { root: { minHeight: 42, borderRadius: 12, paddingInline: 18 } } },
    MuiIconButton: { styleOverrides: { root: { borderRadius: 12 } } },
    MuiPaper: { styleOverrides: { root: { backgroundImage: "none", borderRadius: 16 } } },
    MuiTextField: { defaultProps: { size: "small" } },
    MuiOutlinedInput: { styleOverrides: { root: { minHeight: 46, borderRadius: 12, background: "#FFFFFF" } } },
    MuiTableCell: { styleOverrides: { root: { borderColor: "#E7EBE4" }, head: { color: "#667064", background: "#F8F9F7", fontSize: 12, fontWeight: 750 } } },
    MuiChip: { styleOverrides: { root: { borderRadius: 9, fontWeight: 700 } } },
    MuiAlert: { styleOverrides: { root: { borderRadius: 12 } } },
    MuiDialog: { styleOverrides: { paper: { borderRadius: 18 } } },
    MuiTooltip: { defaultProps: { arrow: true, enterDelay: 500 }, styleOverrides: { tooltip: { borderRadius: 8, fontSize: 12 } } },
  },
});
