import { useState } from "react";
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, Paper, Stack, Tab, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Tabs, TextField, Typography } from "@mui/material";
import AddRoundedIcon from "@mui/icons-material/AddRounded";
import HistoryRoundedIcon from "@mui/icons-material/HistoryRounded";
import { EmptyState, PageHeader, StatCard, StatusChip } from "@/src/components/common";
import { useAuth } from "@/src/modules/auth/hooks/useAuth";
import { citizensApi } from "../api/citizensApi";
import { useCitizens } from "../hooks/useCitizens";
import type { Citizen, CitizenInput } from "../types/citizen.types";
import { vehiclesApi } from "@/src/modules/vehicles/api/vehiclesApi";
import { useVehicles } from "@/src/modules/vehicles/hooks/useVehicles";
import type { Ownership, Vehicle, VehicleInput } from "@/src/modules/vehicles/types/vehicle.types";

const emptyCitizen: CitizenInput = { identificationType: "DPI", identificationNumber: "", firstNames: "", lastNames: "", nit: "", address: "", phone: "", email: "" };
const emptyVehicle: VehicleInput = { plate: "", registrationCard: "", vehicleType: "AUTOMOVIL", brand: "", line: "", color: "", modelYear: null, vinChassis: "", engineNumber: "" };

export function CitizensVehiclesPage() {
  const { hasPermission } = useAuth();
  const [tab, setTab] = useState(0); const [search, setSearch] = useState(""); const [message, setMessage] = useState("");
  const citizens = useCitizens(search); const vehicles = useVehicles(search);
  const [citizenDialog, setCitizenDialog] = useState(false); const [citizenEditing, setCitizenEditing] = useState<Citizen | null>(null); const [citizenForm, setCitizenForm] = useState<CitizenInput>(emptyCitizen);
  const [vehicleDialog, setVehicleDialog] = useState(false); const [vehicleEditing, setVehicleEditing] = useState<Vehicle | null>(null); const [vehicleForm, setVehicleForm] = useState<VehicleInput>(emptyVehicle);
  const [ownerVehicle, setOwnerVehicle] = useState<Vehicle | null>(null); const [ownerCitizenId, setOwnerCitizenId] = useState(""); const [history, setHistory] = useState<Ownership[]>([]);

  async function saveCitizen() { try { if (citizenEditing) await citizensApi.update(citizenEditing.id, citizenForm); else await citizensApi.create(citizenForm); setCitizenDialog(false); setMessage("Ciudadano guardado correctamente."); await citizens.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo guardar."); } }
  async function saveVehicle() { try { if (vehicleEditing) await vehiclesApi.update(vehicleEditing.id, vehicleForm); else await vehiclesApi.create(vehicleForm); setVehicleDialog(false); setMessage("Vehículo guardado correctamente."); await vehicles.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo guardar."); } }
  async function openHistory(vehicle: Vehicle) { setOwnerVehicle(vehicle); setOwnerCitizenId(""); try { setHistory((await vehiclesApi.ownerships(vehicle.id)).data); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo consultar el historial."); } }
  async function assignOwner() { if (!ownerVehicle || !ownerCitizenId) return; try { await vehiclesApi.assignOwner(ownerVehicle.id, ownerCitizenId); await openHistory(ownerVehicle); await vehicles.refresh(); setMessage("Propietario asignado."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo asignar."); } }
  async function endOwner(item: Ownership) { if (!ownerVehicle) return; try { await vehiclesApi.endOwner(ownerVehicle.id, item.id); await openHistory(ownerVehicle); await vehicles.refresh(); setMessage("Propiedad finalizada."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo finalizar."); } }

  return <Box className="module-page">
    <PageHeader eyebrow="Registro municipal" title="Ciudadanos y vehículos" description="Padrón operativo conectado a Express y MySQL, con permisos, auditoría e historial de propietarios." />
    {message && <Alert severity={message.includes("correctamente") || message.includes("asignado") || message.includes("finalizada") ? "success" : "info"} onClose={() => setMessage("")} sx={{ mb: 2 }}>{message}</Alert>}
    <Grid container spacing={2} className="stats-grid"><Grid size={{ xs: 12, md: 4 }}><StatCard label="Ciudadanos" value={String(citizens.meta.total)} helper="Registros en MySQL" /></Grid><Grid size={{ xs: 12, md: 4 }}><StatCard label="Vehículos" value={String(vehicles.meta.total)} helper="Placas únicas" /></Grid><Grid size={{ xs: 12, md: 4 }}><StatCard label="Origen" value="MySQL" helper="Sin datos operativos ficticios" /></Grid></Grid>
    <Paper variant="outlined" sx={{ mb: 2 }}><Tabs value={tab} onChange={(_, value: number) => setTab(value)}><Tab label="Ciudadanos" /><Tab label="Vehículos" /></Tabs></Paper>
    <Paper variant="outlined" className="filter-bar"><TextField className="filter-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder={tab === 0 ? "Identificación, NIT o nombre" : "Placa, tarjeta, marca o línea"} />{tab === 0 && hasPermission("citizens.create") && <Button variant="contained" startIcon={<AddRoundedIcon />} onClick={() => { setCitizenEditing(null); setCitizenForm(emptyCitizen); setCitizenDialog(true); }}>Nuevo ciudadano</Button>}{tab === 1 && hasPermission("vehicles.create") && <Button variant="contained" startIcon={<AddRoundedIcon />} onClick={() => { setVehicleEditing(null); setVehicleForm(emptyVehicle); setVehicleDialog(true); }}>Nuevo vehículo</Button>}</Paper>
    {tab === 0 ? <CitizenTable rows={citizens.rows} loading={citizens.loading} error={citizens.error} canEdit={hasPermission("citizens.update")} canStatus={hasPermission("citizens.deactivate")} onEdit={(row) => { setCitizenEditing(row); setCitizenForm({ identificationType: row.identificationType, identificationNumber: row.identificationNumber, firstNames: row.firstNames, lastNames: row.lastNames, nit: row.nit, address: row.address, phone: row.phone, email: row.email }); setCitizenDialog(true); }} onStatus={async (row) => { if (row.status === "ACTIVE") await citizensApi.deactivate(row.id); else await citizensApi.activate(row.id); await citizens.refresh(); }} /> : <VehicleTable rows={vehicles.rows} loading={vehicles.loading} error={vehicles.error} canEdit={hasPermission("vehicles.update")} canStatus={hasPermission("vehicles.deactivate")} onEdit={(row) => { setVehicleEditing(row); setVehicleForm({ plate: row.plate, registrationCard: row.registrationCard, vehicleType: row.vehicleType, brand: row.brand, line: row.line, modelYear: row.modelYear, color: row.color, vinChassis: row.vinChassis, engineNumber: row.engineNumber }); setVehicleDialog(true); }} onStatus={async (row) => { if (row.status === "ACTIVE") await vehiclesApi.deactivate(row.id); else await vehiclesApi.activate(row.id); await vehicles.refresh(); }} onHistory={(row) => void openHistory(row)} />}
    <CitizenDialog open={citizenDialog} editing={citizenEditing} form={citizenForm} setForm={setCitizenForm} onClose={() => setCitizenDialog(false)} onSave={() => void saveCitizen()} />
    <VehicleDialog open={vehicleDialog} editing={vehicleEditing} form={vehicleForm} setForm={setVehicleForm} onClose={() => setVehicleDialog(false)} onSave={() => void saveVehicle()} />
    <Dialog open={Boolean(ownerVehicle)} onClose={() => setOwnerVehicle(null)} fullWidth maxWidth="md"><DialogTitle>Historial de propietarios · {ownerVehicle?.plate}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{hasPermission("vehicle_ownerships.manage") && <Stack direction={{ xs: "column", sm: "row" }} spacing={1}><TextField select fullWidth label="Ciudadano activo" value={ownerCitizenId} onChange={(e) => setOwnerCitizenId(e.target.value)}>{citizens.rows.filter((row) => row.status === "ACTIVE").map((row) => <MenuItem key={row.id} value={row.id}>{row.firstNames} {row.lastNames} · {row.identificationNumber}</MenuItem>)}</TextField><Button variant="contained" onClick={() => void assignOwner()} disabled={!ownerCitizenId || history.some((row) => row.isCurrent)}>Asignar</Button></Stack>}{history.length ? history.map((item) => <Paper key={item.id} variant="outlined" sx={{ p: 2 }}><Stack direction="row" sx={{ justifyContent: "space-between" }}><Box><Typography sx={{ fontWeight: 700 }}>{item.citizenName}</Typography><Typography color="text.secondary">Desde {new Date(item.startedAt).toLocaleDateString()} {item.endedAt ? `hasta ${new Date(item.endedAt).toLocaleDateString()}` : "· vigente"}</Typography></Box>{item.isCurrent && hasPermission("vehicle_ownerships.manage") && <Button onClick={() => void endOwner(item)}>Finalizar</Button>}</Stack></Paper>) : <EmptyState title="Sin propietarios" description="Este vehículo aún no tiene historial de propiedad." />}</Stack></DialogContent><DialogActions><Button onClick={() => setOwnerVehicle(null)}>Cerrar</Button></DialogActions></Dialog>
  </Box>;
}

function CitizenTable({ rows, loading, error, canEdit, canStatus, onEdit, onStatus }: { rows: Citizen[]; loading: boolean; error: string; canEdit: boolean; canStatus: boolean; onEdit: (row: Citizen) => void; onStatus: (row: Citizen) => Promise<void> }) { if (error) return <Alert severity="error">{error}</Alert>; if (!loading && !rows.length) return <EmptyState title="Sin ciudadanos" description="No hay registros que coincidan con la búsqueda." />; return <Paper variant="outlined" className="data-table-card"><TableContainer><Table><TableHead><TableRow><TableCell>Identificación</TableCell><TableCell>Ciudadano</TableCell><TableCell>Contacto</TableCell><TableCell>Estado</TableCell><TableCell align="right">Acciones</TableCell></TableRow></TableHead><TableBody>{rows.map((row) => <TableRow key={row.id}><TableCell>{row.identificationType} · {row.identificationNumber}</TableCell><TableCell><strong>{row.firstNames} {row.lastNames}</strong></TableCell><TableCell>{row.email ?? row.phone ?? "Restringido"}</TableCell><TableCell><StatusChip status={row.status} /></TableCell><TableCell align="right">{canEdit && <Button onClick={() => onEdit(row)}>Editar</Button>}{canStatus && <Button onClick={() => void onStatus(row)}>{row.status === "ACTIVE" ? "Desactivar" : "Activar"}</Button>}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Paper>; }
function VehicleTable({ rows, loading, error, canEdit, canStatus, onEdit, onStatus, onHistory }: { rows: Vehicle[]; loading: boolean; error: string; canEdit: boolean; canStatus: boolean; onEdit: (row: Vehicle) => void; onStatus: (row: Vehicle) => Promise<void>; onHistory: (row: Vehicle) => void }) { if (error) return <Alert severity="error">{error}</Alert>; if (!loading && !rows.length) return <EmptyState title="Sin vehículos" description="No hay registros que coincidan con la búsqueda." />; return <Paper variant="outlined" className="data-table-card"><TableContainer><Table><TableHead><TableRow><TableCell>Placa</TableCell><TableCell>Vehículo</TableCell><TableCell>Propietario vigente</TableCell><TableCell>Estado</TableCell><TableCell align="right">Acciones</TableCell></TableRow></TableHead><TableBody>{rows.map((row) => <TableRow key={row.id}><TableCell><strong>{row.plate}</strong><Typography component="small" sx={{ display: "block" }}>{row.registrationCard}</Typography></TableCell><TableCell>{row.brand} {row.line} · {row.color}</TableCell><TableCell>{row.currentOwner ? `${row.currentOwner.firstNames} ${row.currentOwner.lastNames}` : "Sin asignar"}</TableCell><TableCell><StatusChip status={row.status} /></TableCell><TableCell align="right">{canEdit && <Button onClick={() => onEdit(row)}>Editar</Button>}{canStatus && <Button onClick={() => void onStatus(row)}>{row.status === "ACTIVE" ? "Desactivar" : "Activar"}</Button>}<Button startIcon={<HistoryRoundedIcon />} onClick={() => onHistory(row)}>Propietarios</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer></Paper>; }
function CitizenDialog({ open, editing, form, setForm, onClose, onSave }: { open: boolean; editing: Citizen | null; form: CitizenInput; setForm: React.Dispatch<React.SetStateAction<CitizenInput>>; onClose: () => void; onSave: () => void }) { const field = (key: keyof CitizenInput, label: string) => <TextField label={label} value={form[key] ?? ""} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value || null }))} />; return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{editing ? "Editar ciudadano" : "Nuevo ciudadano"}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{field("identificationType", "Tipo de identificación")}{field("identificationNumber", "Número de identificación")}{field("firstNames", "Nombres")}{field("lastNames", "Apellidos")}{field("nit", "NIT")}{field("address", "Dirección")}{field("phone", "Teléfono")}{field("email", "Correo")}</Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancelar</Button><Button variant="contained" onClick={onSave}>Guardar</Button></DialogActions></Dialog>; }
function VehicleDialog({ open, editing, form, setForm, onClose, onSave }: { open: boolean; editing: Vehicle | null; form: VehicleInput; setForm: React.Dispatch<React.SetStateAction<VehicleInput>>; onClose: () => void; onSave: () => void }) { const field = (key: keyof VehicleInput, label: string, type = "text") => <TextField label={label} type={type} value={form[key] ?? ""} onChange={(event) => setForm((current) => ({ ...current, [key]: key === "modelYear" ? (event.target.value ? Number(event.target.value) : null) : event.target.value || null }))} />; return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{editing ? "Editar vehículo" : "Nuevo vehículo"}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{field("plate", "Placa")}{field("registrationCard", "Tarjeta de circulación")}{field("vehicleType", "Tipo")}{field("brand", "Marca")}{field("line", "Línea")}{field("modelYear", "Modelo", "number")}{field("color", "Color")}{field("vinChassis", "VIN / chasis")}{field("engineNumber", "Número de motor")}</Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancelar</Button><Button variant="contained" onClick={onSave}>Guardar</Button></DialogActions></Dialog>; }
